### PR TITLE
Prepare for next release v1.4.11

### PR DESCRIPTION
**Pull request by denyeart**
Prepare for next release v1.4.11

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

### CODE REVIEW

**Comment by denyeart** [comment]
Unit tests failing in build of node chaincode TestGenerateDockerBuild in release-1.4.
I'm seeing the same thing in my local environment.
Opened https://jira.hyperledger.org/browse/FAB-18413.

**Comment by sykesm** [comment]
#2350 updates the ccenv Dockerfile to use the correct version of npm for node 8

**Comment by lindluni** [comment]
@Mergifyio rebase

**Comment by lindluni** [comment]
This issue was originally fixed by 69b5487905b3b35258dbc40f95fcccfe8f03cd0b which wasn't backported to 1.4, but it's cropping up in the branches that have 69b5487905b3b35258dbc40f95fcccfe8f03cd0b cherry-picked already as well, I'm debugging that failure in #2356

**Comment by lindluni** [comment]
https://github.com/hyperledger/fabric/pull/2235 <- backporting for CI failure fix may need to cherry pick 69b5487905b3b35258dbc40f95fcccfe8f03cd0b as well for the `grep` bug in the logs, but we will see

**Comment by denyeart** [comment]
@Mergifyio rebase

**Pull request merged**
