### PR TITLE
[FAB-17680] Support removing an org

### PR DESCRIPTION
**Pull request by wuxuer**
Removing an organization from a consortium, application, and orderer.

Signed-off-by: xu wu <wuxu1103@163.com>

#### Type of change

- New feature

#### Related issues
https://jira.hyperledger.org/browse/FAB-17680

### CODE REVIEW

**Comment by wuxuer** [comment]
While running basic checks, CI returned the following error message:
```
Checking with go vet
# github.com/hyperledger/fabric/pkg/config [github.com/hyperledger/fabric/pkg/config.test]
pkg/config/organization_test.go:101:3: unknown field 'ChannelID' in struct literal of type Channel
pkg/config/organization_test.go:133:3: unknown field 'ChannelID' in struct literal of type Channel
```
However, I failed to find any error about organization_test.go, and the CI I was running locally was error-free.
Can someone tell me any useful information about this error? Thanks very much.

**Comment by caod123** [comment]
@hellosmallstone channel ID was removed from the channel struct as part of #962 that was just merged, you can just remove it from your test

**Comment by ryjones** [comment]
I think if you rebase to the tip of the branch, you'll see this

**Comment by wuxuer** [comment]
> @hellosmallstone channel ID was removed from the channel struct as part of #962 that was just merged, you can just remove it from your test

Thanks very much. I have removed "ChannelID" and all the checks have passed.

**Comment by wuxuer** [comment]
> I think if you rebase to the tip of the branch, you'll see this

Based on your suggestions, I saw this error. 
Thanks very much.

**Review by caod123 — APPROVED** [review]

**Pull request merged**
