### PR TITLE
Update smartbft library

### PR DESCRIPTION
**Pull request by HagarMeir**
The smartbft library was moved to hyperledger labs.

### CODE REVIEW

**Comment by denyeart** [comment]
scripts/metrics_doc.sh also needs to be updated for the new package location. Actually the SmartBFT-Go reference can simply be removed since we already grep for "hyperledger" which is a substring of "hyperledger-labs".

**Comment by pfi79** [comment]
> scripts/metrics_doc.sh also needs to be updated for the new package location.

not only that, also this
https://github.com/hyperledger/fabric-lib-go/pull/31

**Comment by denyeart** [comment]
> > scripts/metrics_doc.sh also needs to be updated for the new package location.
> 
> not only that, also this [hyperledger/fabric-lib-go#31](https://github.com/hyperledger/fabric-lib-go/pull/31)

Ah right, I'll merge your fabric-lib-go PR and release v1.1.1.

@HagarMeir After that, you can include the fabric-lib-go update to v1.1.1 in this PR.

**Comment by denyeart** [comment]
@HagarMeir fabric-lib-go v1.1.1 is released, go ahead and update to use it in this PR.

**Comment by pfi79** [comment]
@HagarMeir you should also update [fabric-lib-go](https://github.com/hyperledger/fabric-lib-go/pull/31) in tools/go.mod

**Comment by denyeart** [comment]
> @HagarMeir you should also update [fabric-lib-go](https://github.com/hyperledger/fabric-lib-go/pull/31) in tools/go.mod

In each directory that holds a go.mod, run `go mod tidy` and `go mod vendor` to bring in the new vendored packages.

**Comment by HagarMeir** [comment]
I need to run `./scripts/metrics_doc.sh generate` but can't get it to work for some reason 
`gendoc: error: unrecognized arguments`...

**Comment by pfi79** [comment]
> go mod vendor

go mod vendor in tools? 
Why? I don't think it's necessary.

**Comment by pfi79** [comment]
> I need to run `./scripts/metrics_doc.sh generate` but can't get it to work for some reason
> `gendoc: error: unrecognized arguments`...

Don't. The result will be the same as it already is in the repository.

**Comment by pfi79** [comment]
> I need to run `./scripts/metrics_doc.sh generate` but can't get it to work for some reason `gendoc: error: unrecognized arguments`...

Try using `make generate-metrics-doc`. it pre-installs gendoc with the right version.

**Comment by denyeart** [comment]
> > go mod vendor
> 
> go mod vendor in tools? Why? I don't think it's necessary.

You're right... deleted my comment...

**Review by yacovm — APPROVED** [review]

**Pull request merged**
