### PR TITLE
Eventually before send metric checks in orderer

### PR DESCRIPTION
**Pull request by sykesm**
Sends through the comm layer, much like in gossip, are asynchronous. Some of the metrics tests assumed that the completion of the "OnSubmit" handler implied that the message send processing was complete while, in reality, it only ensure the process was initiated. This left timing windows where assertions related to send metrics would panic because send processing had not completed and captured the related metrics.

Also, the test could not be focused because of the odd use of sub-tests in `assertBiDiCommunicationForChannel` to handle setup of communication streams that were associated with the wrong parent tests. This commit
undoes that craziness and wires the appropriate `*testing.T` to the function to enable assertions at the correct scope.

Finally, to fix one of the issues with the metrics test, this uses a `require.Eventually` to wait for the send metric to be available before making assertions. It's likely there are other windows like this in the tests but we'll leave those for another day.

### CODE REVIEW

**Review by lindluni — APPROVED** [review]

**Comment by yacovm** [comment]
> Sends through the comm layer, much like in gossip, are asynchronous. Some of the metrics tests assumed that the completion of the "OnSubmit" handler implied that the message send processing was complete while, in reality, it only ensure the process was initiated.

OnSubmit is [called](https://github.com/hyperledger/fabric/blob/b2fe5b2a3834e3d70527245597b75516279e5130/orderer/common/cluster/comm.go#L121) when the message [arrives](https://github.com/hyperledger/fabric/blob/b2fe5b2a3834e3d70527245597b75516279e5130/orderer/common/cluster/comm_test.go#L144-L157), not when it is sent. 
Since a message cannot arrive unless it was sent, the assumption in the tests is correct.

**Comment by sykesm** [comment]
> > Sends through the comm layer, much like in gossip, are asynchronous. Some of the metrics tests assumed that the completion of the "OnSubmit" handler implied that the message send processing was complete while, in reality, it only ensure the process was initiated.
> 
> OnSubmit is [called](https://github.com/hyperledger/fabric/blob/b2fe5b2a3834e3d70527245597b75516279e5130/orderer/common/cluster/comm.go#L121) when the message [arrives](https://github.com/hyperledger/fabric/blob/b2fe5b2a3834e3d70527245597b75516279e5130/orderer/common/cluster/comm_test.go#L144-L157), not when it is sent.
> Since a message cannot arrive unless it was sent, the assumption in the tests is correct.

The test is not correct as arrival of the message at the destination and recording of the send metric do not happen at the same time or the same thread of control. The receipt of a message at the destination does not mean that the function calling send or the related processing immediately after it has completed.

Just put a sleep in the code and observe.

```diff
index 32a2ce5e8..ba356a9e5 100644
--- a/orderer/common/cluster/comm.go
+++ b/orderer/common/cluster/comm.go
@@ -543,6 +543,7 @@ func (stream *Stream) sendMessage(request *orderer.StepRequest) {
                startSend := time.Now()
                stream.expCheck.checkExpiration(startSend, stream.Channel)
                err := stream.Cluster_StepClient.Send(request)
+               time.Sleep(time.Second)
                stream.metrics.reportMsgSendTime(stream.Endpoint, stream.Channel, time.Since(startSend))
                return nil, err
        }
diff --git a/orderer/common/cluster/comm_test.go b/orderer/common/cluster/comm_test.go
index fd0fa6cbf..4ae91950f 100644
--- a/orderer/common/cluster/comm_test.go
+++ b/orderer/common/cluster/comm_test.go
@@ -11,6 +11,7 @@ import (
        "crypto/rand"
        "crypto/x509"
        "fmt"
+       "io/ioutil"
        "net"
        "strings"
        "sync"
@@ -266,6 +267,7 @@ func newTestNodeWithMetrics(t *testing.T, metrics cluster.MetricsProvider, tlsCo

        tstSrv.freezeCond.L = &tstSrv.lock

+       flogging.SetWriter(ioutil.Discard)
        tstSrv.c = &cluster.Comm{
                CertExpWarningThreshold: time.Hour,
                SendBufferSize:          1,
@@ -1208,7 +1210,11 @@ func TestMetrics(t *testing.T) {
                        name: "MsgSendTime",
                        runTest: func(t *testing.T, node1, node2 *clusterNode, testMetrics *testMetrics) {
                                assertBiDiCommunication(t, node1, node2, testReq)
-                               require.Eventually(t, func() bool { return testMetrics.msgSendTime.ObserveCallCount() > 0 }, time.Second, 10*time.Millisecond)
+                               // require.Eventually(t, func() bool { return testMetrics.msgSendTime.ObserveCallCount() > 0 }, time.Second, 10*time.Millisecond)
+                               if testMetrics.msgSendTime.ObserveCallCount() == 0 {
+                                       fmt.Println("Failing...")
+                                       panic("boom")
+                               }
                                require.Equal(t, 1, testMetrics.msgSendTime.ObserveCallCount())
                                require.Equal(t, []string{"host", node2.nodeInfo.Endpoint, "channel", testChannel}, testMetrics.msgSendTime.WithArgsForCall(0))
                        },
```

With a delay between the completion of `Send` and recording the metric, the test fails all the time.

```
go test -v -run TestMetrics/MsgSendTime -count 1 -race .
=== RUN   TestMetrics
=== RUN   TestMetrics/MsgSendTime
    comm_test.go:1375: 1->2
    comm_test.go:1375: 2->1
Failing...
--- FAIL: TestMetrics (0.03s)
    --- FAIL: TestMetrics/MsgSendTime (0.03s)
panic: boom [recovered]
        panic: boom

goroutine 23 [running]:
testing.tRunner.func1.1(0x1107300, 0x13e36f0)
        /usr/local/go/src/testing/testing.go:988 +0x452
testing.tRunner.func1(0xc000562b40)
        /usr/local/go/src/testing/testing.go:991 +0x600
panic(0x1107300, 0x13e36f0)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/hyperledger/fabric/orderer/common/cluster_test.TestMetrics.func5(0xc000562b40, 0xc0001ec000, 0xc0001ec580, 0xc0003d6000)
        /home/sykesm/fabric/orderer/common/cluster/comm_test.go:1216 +0x438
github.com/hyperledger/fabric/orderer/common/cluster_test.TestMetrics.func7(0xc000562b40)
        /home/sykesm/fabric/orderer/common/cluster/comm_test.go:1285 +0x624
testing.tRunner(0xc000562b40, 0xc000542760)
        /usr/local/go/src/testing/testing.go:1039 +0x1ec
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1090 +0x701
FAIL    github.com/hyperledger/fabric/orderer/common/cluster    0.206s
FAIL
```

As always, I'd prefer those who know the code best fix the flakes. This particular issue was highlighted along with another in the consensus package this morning so there's plenty to do.

**Comment by sykesm** [comment]
Alternatively, to highlight the order of operations:

```diff
diff --git a/orderer/common/cluster/comm.go b/orderer/common/cluster/comm.go
index 32a2ce5e8..3121f33ba 100644
--- a/orderer/common/cluster/comm.go
+++ b/orderer/common/cluster/comm.go
@@ -542,8 +542,11 @@ func (stream *Stream) sendMessage(request *orderer.StepRequest) {
        f := func() (*orderer.StepResponse, error) {
                startSend := time.Now()
                stream.expCheck.checkExpiration(startSend, stream.Channel)
+               fmt.Println("Sending request...")
                err := stream.Cluster_StepClient.Send(request)
+               fmt.Println("Sent request...")
                stream.metrics.reportMsgSendTime(stream.Endpoint, stream.Channel, time.Since(startSend))
+               fmt.Println("Reported metric...")
                return nil, err
        }

diff --git a/orderer/common/cluster/comm_test.go b/orderer/common/cluster/comm_test.go
index fd0fa6cbf..617ad11d6 100644
--- a/orderer/common/cluster/comm_test.go
+++ b/orderer/common/cluster/comm_test.go
@@ -11,6 +11,7 @@ import (
        "crypto/rand"
        "crypto/x509"
        "fmt"
+       "io/ioutil"
        "net"
        "strings"
        "sync"
@@ -147,12 +148,14 @@ func (cn *clusterNode) Step(stream orderer.Cluster_StepServer) error {
        if err != nil {
                return err
        }
+       fmt.Println("Message received...")
        if submitReq := req.GetSubmitRequest(); submitReq != nil {
                return cn.c.DispatchSubmit(stream.Context(), submitReq)
        }
        if err := cn.c.DispatchConsensus(stream.Context(), req.GetConsensusRequest()); err != nil {
                return err
        }
+       fmt.Println("Sending reply...")
        return stream.Send(&orderer.StepResponse{})
 }

@@ -266,6 +269,7 @@ func newTestNodeWithMetrics(t *testing.T, metrics cluster.MetricsProvider, tlsCo

        tstSrv.freezeCond.L = &tstSrv.lock

+       flogging.SetWriter(ioutil.Discard)
        tstSrv.c = &cluster.Comm{
                CertExpWarningThreshold: time.Hour,
                SendBufferSize:          1,
@@ -1208,7 +1212,10 @@ func TestMetrics(t *testing.T) {
                        name: "MsgSendTime",
                        runTest: func(t *testing.T, node1, node2 *clusterNode, testMetrics *testMetrics) {
                                assertBiDiCommunication(t, node1, node2, testReq)
-                               require.Eventually(t, func() bool { return testMetrics.msgSendTime.ObserveCallCount() > 0 }, time.Second, 10*time.Millisecond)
+                               // require.Eventually(t, func() bool { return testMetrics.msgSendTime.ObserveCallCount() > 0 }, time.Second, 10*time.Millisecond)
+                               if testMetrics.msgSendTime.ObserveCallCount() == 0 {
+                                       panic("boom")
+                               }
                                require.Equal(t, 1, testMetrics.msgSendTime.ObserveCallCount())
                                require.Equal(t, []string{"host", node2.nodeInfo.Endpoint, "channel", testChannel}, testMetrics.msgSendTime.WithArgsForCall(0))
                        },
```

Run things in a loop and wait for the failure:
```
$ go test -v -run TestMetrics/MsgSendTime -count 1000 -race .
...
=== RUN   TestMetrics
=== RUN   TestMetrics/MsgSendTime
    comm_test.go:1376: 1->2
Sending request...
Message received...
    comm_test.go:1376: 2->1
Sending request...
Sent request...
Reported metric...
Message received...
--- FAIL: TestMetrics (0.04s)
    --- FAIL: TestMetrics/MsgSendTime (0.04s)
panic: boom [recovered]
        panic: boom

goroutine 2612 [running]:
testing.tRunner.func1.1(0x1107300, 0x13e37b0)
        /usr/local/go/src/testing/testing.go:988 +0x452
testing.tRunner.func1(0xc000136240)
        /usr/local/go/src/testing/testing.go:991 +0x600
panic(0x1107300, 0x13e37b0)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/hyperledger/fabric/orderer/common/cluster_test.TestMetrics.func5(0xc000136240, 0xc0000de000, 0xc0000de580, 0xc0000ae700)
        /home/sykesm/fabric/orderer/common/cluster/comm_test.go:1217 +0x3c4
github.com/hyperledger/fabric/orderer/common/cluster_test.TestMetrics.func7(0xc000136240)
        /home/sykesm/fabric/orderer/common/cluster/comm_test.go:1286 +0x624
testing.tRunner(0xc000136240, 0xc0003fed40)
        /usr/local/go/src/testing/testing.go:1039 +0x1ec
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1090 +0x701
FAIL    github.com/hyperledger/fabric/orderer/common/cluster    3.778s
FAIL
```

**Comment by yacovm** [comment]
> The test is not correct as arrival of the message at the destination and recording of the send metric do not happen at the same time or the same thread of control. 

Yes, indeed the problem is that the recording takes place after queuing it into the gRPC buffer. I thought you meant something entirely else in your commit message

**Pull request merged**
