### PR TITLE
Add readthedocs config file

### PR DESCRIPTION
**Pull request by denyeart**
Add readthedocs config file.

For more background see https://blog.readthedocs.com/migrate-configuration-v2/

### CODE REVIEW

**Review by ale-linux — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergifyio backport release-2.5

**Comment by denyeart** [comment]
@Mergifyio backport release-2.4

**Comment by denyeart** [comment]
@Mergifyio backport release-2.3

**Comment by denyeart** [comment]
@Mergifyio backport release-2.2

**Pull request merged**
