### PR TITLE
Updating chaincode document.

### PR DESCRIPTION
**Pull request by binhn**
FAB-17445 Chaincode TLS property keys have been changed in the
code. This commit keeps the document uptodate with those changes.

Closes #FAB-17445

Signed-off-by: Binh Nguyen <binh1010010110@gmail.com>

### CODE REVIEW

**Comment by joealewine** [comment]
@pamandrejko

**Comment by pamandrejko** [comment]
@muralisrini @sykesm Are you OK with these changes?

**Comment by muralisrini** [comment]
@pamandrejko lgtm

**Review by muralisrini — APPROVED** [review]
lgtm

**Pull request merged**
