### PR TITLE
Fix the style-guides directory naming scheme

### PR DESCRIPTION
**Pull request by lindluni**
This change removes the duplicate style guide directory that is the same name as the other, just with a different case. This was introduced via a documentation cherry pick and causes folder reconciliation issues on case insensitive systems like OSX

#### Type of change

- Bug fix

### CODE REVIEW

**Review by manish-sethi — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ale-linux — APPROVED** [review]

**Comment by guoger** [comment]
https://gerrit.hyperledger.org/r/c/fabric/+/32812 magically prevents IT flake from happening for a long period on master branch. we probably need to cherry-pick that to 1.4

**Review by mastersingh24 — APPROVED** [review]

**Comment by mastersingh24** [comment]
not sure why integration tests are timing out, but going to override and merge this given it's only a doc change

**Pull request merged**
