### PR TITLE
Add staticcheck static analysis and style checks in CI

### PR DESCRIPTION
**Pull request by sykesm**
Based on some interactions in another PR, these commits fix issues flagged by staticcheck and enable these checks in CI.

### CODE REVIEW

**Review by jyellick — APPROVED** [review]
Big but rote -- LGTM once CI starts behaving

**Comment by lindluni** [comment]
I need to fix CI, Dave and I reassigned some of the service connections yesterday and they were associated by their SHA, not by their name, so AZP can't find the association anymore

**Comment by denyeart** [comment]
BTW CI passed after Matt's re-trigger:
https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=29234&view=results

It must just be having trouble posting back.

**Pull request merged**
