### PR TITLE
[FAB-17136] Fix the typo error

### PR DESCRIPTION
**Pull request by bjzhang03**
This is fix #FAB-17136

When I read the resource code, I found some typo error, and I want to solve it.

Signed-off-by: bjzhang <bjzhang1991@gmail.com>

#### Type of change

- Documentation update

#### Description

Fix some spelling error

#### Related issues

https://jira.hyperledger.org/browse/FAB-17136

### CODE REVIEW

**Comment by bjzhang03** [comment]
run UnitTests

**Comment by bjzhang03** [comment]
run UnitTests

**Review by ale-linux — DISMISSED** [review]
I fixed two small nits

**Comment by ryjones** [comment]
DCO on both commits needs fixed

**Review by guoger — APPROVED** [review]
/azp-run

i don't exactly understand the review process here... if a maintainer added a new commit, do we still squash?

**Comment by bjzhang03** [comment]
because I fix the dco problem，make the mistake。
I am so sorry。

**Comment by guoger** [comment]
@bjzhang03 no apology needed, my comment up there wasn't about you, but a general question w.r.t review process

**Review by mastersingh24 — APPROVED** [review]

**Review by mastersingh24 — APPROVED** [review]

**Pull request merged**
