### PR TITLE
Advice for translators, PRs and tools

### PR DESCRIPTION
**Pull request by ODOWDAIBM**
Signed-off-by: Anthony O'Dowd <a_o-dowd@uk.ibm.com>

#### Type of change

- Documentation update

#### Description

Strengthened advice on PRs and signing, plus better link
Advisory translation tools for first pass

#### Additional details

Feedback from doc workgroups

### CODE REVIEW

**Comment by ODOWDAIBM** [comment]
- PR advice: https://hyperledger-fabric--1583.org.readthedocs.build/en/1583/docs_guide.html#making-a-pr
- Translation tools: https://hyperledger-fabric--1583.org.readthedocs.build/en/1583/international_languages.html#translation-tools

**Comment by ODOWDAIBM** [comment]
@aneenaalexander @yukiknd @naonishijima Thanks for these suggestions on translation tools.  They are now added to the docs.

**Review by pamandrejko — APPROVED** [review]
Thanks Anthony!

**Comment by pamandrejko** [comment]
@Mergifyio backport release-2.2

**Comment by pamandrejko** [comment]
@Mergifyio backport release-2.1

**Comment by aneenaalexander** [comment]
> @aneenaalexander @yukiknd @naonishijima Thanks for these suggestions on translation tools. They are now added to the docs.

@ODOWDAIBM This will be helpful for new language translation teams.

**Pull request merged**
