### PR TITLE
check if desired version of samples exists

### PR DESCRIPTION
**Pull request by nasermirzaei89**
#### Type of change

- Improvement (improvement to code, performance, etc)

#### Description

`bootstrap.sh` script uses `VERSION` of fabric repo in checkout fabric-samples. So, we need to check if it exists in fabric-samples.

### CODE REVIEW

**Comment by lindluni** [comment]
The correct behavior of this script when a non-existing version of fabric-samples is used is for the checkout to fail. This will cause the latest master branch to be used (which is the intended behavior). These versions should always line up except for when master should be used (which is the current case until we tag v2.2.0 in the next week or so)

If we are going to do anything we should do a `git ls-remote --tags origin refs/tags/v<version>` to check if the tag exists, and do a checkout if it exists, otherwise print a message that its `fabric-samples v<version> does not exist, defaulting master`

**Comment by nasermirzaei89** [comment]
@btl5037 signed off

**Comment by ale-linux** [comment]
@nasermirzaei89 could you pls address the comments from @btl5037? Or have they already been addressed to your satisfaction @btl5037?

**Review by lindluni — APPROVED** [review]

**Comment by WaleedMortaja** [comment]
@lindluni @denyeart should this be backported to release-2.2?

**Comment by denyeart** [comment]
@WaleedMortaja No need to backport since the download doc for all versions directs users to the bootstrap.sh script in main branch.
In general, when a PR is merged the maintainers consider whether it should be backported at that time. There is no need to identify and ask about every PR that is not backported since the maintainers have already considered the backport and made a decision. That being said, if you have a strong need for something to be backported to a certain release you are welcome to open a backport PR.

**Pull request merged**
