### PR TITLE
change workflow

### PR DESCRIPTION
**Pull request by pfi79**
because of runner fabric-ubuntu, my fork stopped passing checks, tests and integration tests
Снимок экрана 2023-10-21 в 23 41 55

here is my solution, if anyone has a better one, you are welcome.

### CODE REVIEW

**Comment by C0rWin** [comment]
Is this something related to your own fork? Or this is a general problem? Could you put more context, what exactly the problem?

**Comment by pfi79** [comment]
> Is this something related to your own fork? Or this is a general problem? Could you put more context, what exactly the problem?

It seems to me that this is a common problem.

Here's an example of your page.
Checks with the same features as mine don't work

image

**Comment by pfi79** [comment]
Normal runners don't find the fabric-ubuntu-20.04 image.
I understand that the hyperledger/fabric project has migrated to its own runners. 
And they are not available for forks.

My solution will allow hyperledger/fabric to use their own runners, the rest of us to use shared runners.

**Comment by bestbeforetoday** [comment]
Rather than duplicating the build jobs, how about having a [repository variable](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository) defined with the runner name and the workflows use that, or a default if not set. For example:

```
runs-on: ${{ vars.RUNNER || ‘ubuntu-20.04’ }}
```

**Comment by pfi79** [comment]
> Rather than duplicating the build jobs, how about having a [repository variable](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository) defined with the runner name and the workflows use that, or a default if not set. For example:
> 
> ```
> runs-on: ${{ vars.RUNNER || ‘ubuntu-20.04’ }}
> ```

You are right, that would be the best solution. But I don't have access to the "vars.RUNNER" setting in hyperledger/fabric.

If you can set this variable now, I am willing to modify my fix

**Comment by bestbeforetoday** [comment]
I don’t have access with this repository either.

**Comment by denyeart** [comment]
@bestbeforetoday @pfi79 I have set a repository variable:
`RUNNER=fabric-ubuntu-20.04`

Please try it out!

**Comment by pfi79** [comment]
> @bestbeforetoday @pfi79 I have set a repository variable: `RUNNER=fabric-ubuntu-20.04`
> 
> Please try it out!

I did.

**Comment by pfi79** [comment]
It worked.
@bestbeforetoday, thank you so much for the idea.

**Comment by pfi79** [comment]
@denyeart for some reason it's not working.

```
2023-10-26T00:58:54.7373515Z Evaluating target
2023-10-26T00:58:54.7374425Z Evaluating: (vars.RUNNER || 'ubuntu-20.04')
2023-10-26T00:58:54.7374511Z ##[debug]Evaluating Or:
2023-10-26T00:58:54.7374541Z ##[debug]..Evaluating Index:
2023-10-26T00:58:54.7374564Z ##[debug]....Evaluating vars:
2023-10-26T00:58:54.7374598Z ##[debug]....=> null
2023-10-26T00:58:54.7374633Z ##[debug]..=> null
2023-10-26T00:58:54.7374654Z ##[debug]..Evaluating String:
2023-10-26T00:58:54.7374676Z ##[debug]..=> 'ubuntu-20.04'
2023-10-26T00:58:54.7374714Z ##[debug]=> 'ubuntu-20.04'
2023-10-26T00:58:54.7374757Z Expanded: (null || 'ubuntu-20.04')
2023-10-26T00:58:54.7374782Z Result: 'ubuntu-20.04'
```

**Comment by pfi79** [comment]
@denyeart 
I added the repository variable according to the [instructions](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository). And it worked.

Please check if the repository variable is set correctly.

**Comment by denyeart** [comment]
@pfi79  I followed the same instructions yesterday and my value got added to the repository settings:

image

**Comment by pfi79** [comment]
> @pfi79 I followed the same instructions yesterday and my value got added to the repository settings:
> 
> image

Strange, the test isn't over yet, of course. But again fabric-ubuntu-20.04 was not found.

**Comment by pfi79** [comment]
Found it. Configuration variables are not visible from fork during pull_request. 
Here's [the discussion](https://github.com/orgs/community/discussions/44322)

So for now, the "${{ vars.RUNNER || ‘ubuntu-20.04’ }}" option doesn't work.

**Comment by bestbeforetoday** [comment]
Disappointing that the repository variable is not visible to PR runs. Perhaps you can still do better than duplicating the whole job definition. Maybe this?

```
runs-on: ${{ GITHUB_REPOSITORY_OWNER == ‘hyperledger’ && ‘fabric-ubuntu-20.04’ || ‘ubuntu-20.04’ }}
```

**Comment by pfi79** [comment]
> Disappointing that the repository variable is not visible to PR runs. Perhaps you can still do better than duplicating the whole job definition. Maybe this?

All right, I'll check it out

**Comment by pfi79** [comment]
> Disappointing that the repository variable is not visible to PR runs. Perhaps you can still do better than duplicating the whole job definition. Maybe this?
> 
> ```
> runs-on: ${{ GITHUB_REPOSITORY_OWNER == ‘hyperledger’ && ‘fabric-ubuntu-20.04’ || ‘ubuntu-20.04’ }}
> ```

Thank you. Everything worked just fine.

**Review by denyeart — APPROVED** [review]

**Pull request merged**
