### PR TITLE
For avoiding SERVICE_UNAVAILABLE -- no Raft leader 

### PR DESCRIPTION
**Pull request by senthilkumar-ofs**
#### Type of change

- Bug fix
- New feature
- Improvement (improvement to code, performance, etc)
- Test update
- Documentation update

### CODE REVIEW

**Review by senthilkumar-ofs — COMMENTED** [review]
For avoiding SERVICE_UNAVAILABLE -- no Raft leader

**Comment by lindluni** [comment]
We require signed commits, please follow the instructions here to sign your changes: https://github.com/hyperledger/fabric/pull/421/checks

**Review by guoger — CHANGES_REQUESTED** [review]
Thanks for contribution! Please update PR message to reflect the intend of this change.

Also, i wonder why this change is needed, as single node orderer should also work. Are you seeing any errors running the sample?

**Comment by senthilkumar-ofs** [comment]
> Thanks for contribution! Please update PR message to reflect the intend of this change.
> 
> Also, i wonder why this change is needed, as single node orderer should also work. Are you seeing any errors running the sample?

Yes. While running sample(first-network), got the above error. So updated the document

**Comment by guoger** [comment]
> > Thanks for contribution! Please update PR message to reflect the intend of this change.
> > Also, i wonder why this change is needed, as single node orderer should also work. Are you seeing any errors running the sample?
> 
> Yes. While running sample(first-network), got the above error. So updated the document

normally it takes a few seconds for a leader to be elected, depending on election timeout config. So you may see this error if a channel has just been started, and you'll need to retry. Plus, adding more orderers would not solve the "problem".

Are you seeing this error constantly after several retry?

**Comment by guoger** [comment]
close due to inactivity. pls reopen if needed.

**Pull request closed without merging**
