### PR TITLE
Bump fabric dependencies

### PR DESCRIPTION
**Pull request by sykesm**
Pickup new version of [hyperledger/fabric-protos-go].

There appears to be an issue with [hyperledger/fabric-chaincode-go] in master so choosing a commit that works.

[hyperledger/fabric-protos-go]: https://github.com/hyperledger/fabric-protos-go
[hyperledger/fabric-chaincode-go]: https://github.com/hyperledger/fabric-chaincode-go

### CODE REVIEW

**Review by jyellick — DISMISSED** [review]

**Comment by sykesm** [comment]
Looks like the fabric-chaincode-go dependencies may not be ready yet. Looking...

**Comment by sykesm** [comment]
Opened FAB-17376 for the flake in etcdraft.

**Review by mastersingh24 — APPROVED** [review]

**Pull request merged**
