### PR TITLE
[FAB-18005] remove couchDB index warming

### PR DESCRIPTION
**Pull request by dongmingh**
This PR is to remove the index warming in fabric since
couchDB 3.0 supports automatic index warming.

Signed-off-by: Dongming Hwang <dongming@ibm.com>

#### Type of change

- Bug fix
- New feature
- Improvement (improvement to code, performance, etc)
- Test update
- Documentation update

### CODE REVIEW

**Comment by lindluni** [comment]
Missed this one index here: https://github.com/hyperledger/fabric/blob/master/core/ledger/kvledger/txmgmt/statedb/statecouchdb/couchdb_test.go#L128

**Comment by lindluni** [comment]
Also doc that needs to be removed as well in another commit. This references index warming: docs/source/couchdb_tutorial.rst

**Review by sykesm — APPROVED** [review]

**Review by denyeart — APPROVED** [review]
gossip unit test flake, re-running (I thought gossip unit tests didn't run...)

**Comment by sykesm** [comment]
> gossip unit test flake, re-running (I thought gossip unit tests didn't run...)

The gossip tests run when a package gossip depends on changes. This PR included a change to `github.com/hyperledger/fabric/core/ledger` which is used by `gossip/util` and `gossip/privdata`.

**Pull request merged**
