### PR TITLE
bump go 1.22.5

### PR DESCRIPTION
**Pull request by pfi79**

### CODE REVIEW

**Comment by denyeart** [comment]
Broken link checker failure can be ignored...

**Review by denyeart — APPROVED** [review]

**Comment by pfi79** [comment]
> Broken link checker failure can be ignored...

I'm restarting Unit test. There's an error again.

**Comment by denyeart** [comment]
@pfi79 I re-ran the failures. I assume you don't have access to re-run yourself from the failed github action page. I granted you 'triage' privilege a while back on fabric repositories, but you may need maintainer 'write' privilege to re-run (I don't recall).

**Comment by pfi79** [comment]
> @pfi79 I re-ran the failures. I assume you don't have access to re-run yourself from the failed github action page. I granted you 'triage' privilege a while back on fabric repositories, but you may need maintainer 'write' privilege to re-run (I don't recall).

we restart it like this:
```
git commit --amend --signoff   
git push --force
```

**Comment by denyeart** [comment]
> > @pfi79 I re-ran the failures. I assume you don't have access to re-run yourself from the failed github action page. I granted you 'triage' privilege a while back on fabric repositories, but you may need maintainer 'write' privilege to re-run (I don't recall).
> 
> we restart it like this:
> 
> ```
> git commit --amend --signoff   
> git push --force
> ```

That works. You can also close/re-open to re-trigger all of them. If I see a failure I'll re-run just that test for you.

Merging...

**Comment by satota2** [comment]
@Mergifyio backport release-2.5

**Pull request merged**
