### PR TITLE
Updated setting up environment documentation to reflect "brew cask" no longer being a valid command

### PR DESCRIPTION
**Pull request by tlalka**
#### Type of change

- Documentation update

#### Description

Replaced "brew cask install --appdir=“/Applications” docker" with "brew install --cask docker"

Cask is no longer a brew command. When you want to install a Cask, you just do brew install or brew install --cask instead of brew cask install.

#### Additional details

Change can be previewed here:
https://tlalka-fabric-fork.readthedocs.io/en/latest/dev-setup/devenv.html

#### Related issues

N/A

### CODE REVIEW

**Review by denali49 — DISMISSED** [review]
ltgm, and good catch.  Thanks for your contribution!

**Review by denali49 — COMMENTED** [review]
Don't forget to add your developer certificate of origin (DCO) sign-off as required for submitting PRs.  Also, congratulations on your first contribution to Fabric!

**Comment by tlalka** [comment]
@denali49 I've already forgotten to (oops). Can you help me fix that? I tried following the instructions on the checks page, but it hasn't made any difference.

**Comment by denali49** [comment]
> @denali49 I've already forgotten to (oops). Can you help me fix that? I tried following the instructions on the checks page, but it hasn't made any difference.

Sure, just issue the commit with `git commit -s` 
the `-s` flag is the sign-off flag that will attach your public github username to the commit.  There are additional instructions here https://hyperledger-fabric.readthedocs.io/en/release-2.3/github/github.html#committing-and-pushing-changes-to-your-forked-repository

You can also checkout the execellent reference @ryjones put together here https://wiki.hyperledger.org/display/CA/Use+GitHub+for+Windows+and+VSCode

**Comment by tlalka** [comment]
I will re-submit this with the correct signature

**Pull request closed without merging**
