### PR TITLE
Update secured_private_asset_transfer_tutorial.md

### PR DESCRIPTION
**Pull request by ichsteffen**
Fixed typo

#### Type of change

- Bug fix in documentation 

#### Description

Org1 was mentioned twice instead of Org1 and Org2

### CODE REVIEW

**Review by lindluni — DISMISSED** [review]

**Comment by lindluni** [comment]
Thank you for the contribution @ichsteffen, you will need to add you signature by following the steps outlined here before this change can be made: https://github.com/hyperledger/fabric/pull/2636/checks?check_run_id=2737965050

**Review by denali49 — CHANGES_REQUESTED** [review]
Please sign your commit with `git commit -s` so your DCO will pass checks.  Thank you for your contribution.  The content of your change is fine and can be approved and merged as soon as you sign your commit.

**Review by denali49 — APPROVED** [review]
lgtm, thanks for your contribution @ichsteffen!

**Review by mastersingh24 — APPROVED** [review]
LGTM.  Thanks!

**Comment by denyeart** [comment]
@Mergifyio backport release-2.3

**Comment by denyeart** [comment]
@Mergifyio backport release-2.2

**Pull request merged**
