### PR TITLE
modify the errors notification

### PR DESCRIPTION
**Pull request by bjzhang03**
Signed-off-by: bjzhang <bjzhang1991@gmail.com>

#### Type of change
- Documentation update

#### Description

When I run the fabric,I found the mistake in errors,so I fix it.

### CODE REVIEW

**Review by C0rWin — APPROVED** [review]
thanks for contribution!

**Review by sykesm — CHANGES_REQUESTED** [review]
It’s actually a singular subsystem. There is one.

**Comment by sykesm** [comment]
@bjzhang03 - I was attempting to reopen this and fix it on your behalf but was unsuccessful.

**Comment by bjzhang03** [comment]
> @bjzhang03 - I was attempting to reopen this and fix it on your behalf but was unsuccessful.
I also attempt to reopen this

**Pull request closed without merging**
