### PR TITLE
Fix some typo in docs

### PR DESCRIPTION
**Pull request by naonishijima**
#### Type of change
- Documentation update

#### Description
This CR fixes the following some typo in docs.
- chainocode -> chaincode
- chainode -> chaincode
- lifecyle -> lifecycle
- Hyperlegder -> Hyperledger
- chanel -> channel
- scructured -> structured
- demostrate -> demonstrate
- certficates -> certificates
- how how -> how
- the the -> the
- a a -> a
- thefollowing -> the following

### CODE REVIEW

**Review by lindluni — APPROVED** [review]

**Comment by lindluni** [comment]
Thank you for the contribution! Fixing our grammar and spelling is always welcome!

**Comment by btl5037** [comment]
@Meregifyio backport release-2.1

**Comment by btl5037** [comment]
@Meregifyio backport release-2.0

**Comment by btl5037** [comment]
@Meregifyio backport release-1.4

**Comment by lindluni** [comment]
@Mergifyio backport release-2.1

**Comment by lindluni** [comment]
@Mergifyio backport release-2.0

**Comment by lindluni** [comment]
@Mergifyio backport release-1.4

**Pull request merged**
