### PR TITLE
Fix test net codeblock typo

### PR DESCRIPTION
**Pull request by nikhil550**
Signed-off-by: NIKHIL E GUPTA <negupta@us.ibm.com>

#### Type of change

- Documentation update

#### Description

Typo fix

### CODE REVIEW

**Review by lindluni — APPROVED** [review]

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.1

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.0

**Comment by lindluni** [comment]
@Mergifyio backport release-2.1

**Comment by lindluni** [comment]
@Mergifyio backport release-2.0

**Pull request merged**
