### PR TITLE
removing -a from docker ps command as it lists stopped containers also

### PR DESCRIPTION
**Pull request by RahulRoy090791**
Signed-off-by: System Administrator <root@Rahuls-MacBook-Air.local>

Removing -a from 'docker ps' commnand, since it lists stopped containers also

#### Type of change

- Bug fix
- New feature
- Improvement (improvement to code, performance, etc)
- Test update
- Documentation update

### CODE REVIEW

**Review by lindluni — CHANGES_REQUESTED** [review]
I think instead of removing the `-a` flag, if you feel strongly about this we should remove the word `running` instead.  It's not uncommon for the containers to crash and removing the flag will prevent users from seeing the crashed containers.

**Comment by RahulRoy090791** [comment]
> I think instead of removing the `-a` flag, if you feel strongly about this we should remove the word `running` instead. It's not uncommon for the containers to crash and removing the flag will prevent users from seeing the crashed containers.

Yes, that is also a good suggestion, we can remove the text 'running'.

**Comment by denyeart** [comment]
I agree with @lindluni , especially for newbies it is good to teach them about `-a` so that they see the full picture of containers.

**Comment by nikhil550** [comment]
Maybe the following language is good enough?

Run the following command to list all of th Docker containers on your machine. You should see the three nodes that were created by the `network.sh` script:
```
docker ps -a 
```

maybe we can add a sentence about crashed nodes, but I think it would be better to assume that everything worked given that this is targeted to beginners.

**Comment by lindluni** [comment]
Closing as abandoned

**Pull request closed without merging**
