### PR TITLE
Fix organizations typo

### PR DESCRIPTION
**Pull request by Taur1ne**
#### Type of change

- Documentation update

#### Description

Fix typo

### CODE REVIEW

**Comment by caod123** [comment]
Hello @Taur1ne, thanks for the PR! Per the [contribution guidelines](https://hyperledger-fabric.readthedocs.io/en/latest/github/github.html#commiting-and-pushing-changes-to-your-forked-repository) for Hyperledger Fabric, please sign off on the commit and force push back to this branch:
```
git commit --amend -s --no-edit
git push -f Taur1ne master
```

**Comment by Taur1ne** [comment]
@caod123 - I think I've resolved the items above. Thanks!

**Review by lindluni — APPROVED** [review]

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.1

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.0

**Comment by nikhil550** [comment]
@Mergifyio backport release-1.4

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.0

**Pull request merged**
