### PR TITLE
Orderer v3: fix IsChannelMember to match public keys

### PR DESCRIPTION
**Pull request by tock-ibm**
#### Type of change

- Bug fix
- Improvement (improvement to code, performance, etc)
- 
#### Description

Orderer v3: fix IsChannelMember to match public keys

- Remove system channel usage from:  `integration/raft/cft_test.go` use-case: "disregards certificate renewal if only the validity period changed"
- Fix a bug in IsChannelMember  that manifested in that test
- Addresses the bug reported in issue #3998

#### Related issues

Addresses: #3998 
Parent issue: #3515

### CODE REVIEW

**Review by yacovm — APPROVED** [review]

**Comment by yacovm** [comment]
@denyeart  should we not backport this?

**Comment by denyeart** [comment]
@yacovm Yes in general bug fixes should be backported to release-2.5, and if applicable and bad enough, also to release-2.2 since these are the two LTS releases.
The severity of this one is not clear to me... what is the ultimate impact on the system of the bug? Please make that clear so that we can mention in the release notes.
The maintainer that reviews and merges a fix is typically in the best position to assess whether a backport is important, and then perform the backport(s) or request the backport from the PR contributor.

**Comment by yacovm** [comment]
Look at https://github.com/hyperledger/fabric/issues/3998 it sums up pretty nicely

**Comment by yacovm** [comment]
@Mergifyio backport release-2.5

**Comment by denyeart** [comment]
@tock-ibm or @yacovm I see #3998, but could you add the overall system impact from user perspective in the #3998 description. e.g. will this just be a problem for a single node, does a restart solve it, is there a workaround, or is this a critical problem for the whole ordering service? I can then add it to the release notes.

**Comment by yacovm** [comment]
The added node doesn't see itself part of the channel so it will never evolve from a follower to a consenter unless you do a config update.

**Comment by dviejokfs** [comment]
@yacovm @denyeart 
I think there should be a release for 2.4, maybe as 2.4.7.

It's preventing certificates to be renewed using the 2.4.6 version of the orderer.

**Comment by denyeart** [comment]
@tock-ibm The auto backport to release-2.5 failed due to conflicts, I've closed it. Could you do a manual cherry-pick to release-2.5 and release-2.4?

**Comment by denyeart** [comment]
@tock-ibm ,
Note that @dviejokfs is attempting the backport, please help to review #4070

**Pull request merged**
