### PR TITLE
fixed typo.

### PR DESCRIPTION
**Pull request by Shubham-koli**
Signed-off-by: Shubham Koli shubham.koli@outlook.in

#### Type of change

- Documentation update

### CODE REVIEW

**Review by yacovm — DISMISSED** [review]
this is not a typo.... but OK.

**Review by nikhil550 — DISMISSED** [review]

**Review by guoger — DISMISSED** [review]
Thx for your contribution

DCO needs to be fixed, you could `git commit --amend --signoff` then do a force push.

Also, pls remove unneeded fields in commit message template

**Comment by Shubham-koli** [comment]
Signed-off-by: Shubham Koli shubham.koli@outlook.in

**Review by kchristidis — DISMISSED** [review]

**Comment by guoger** [comment]
DCO problem has not been fixed, make sure you do `git commit --amend -s` (not manually adding the sign off line)

**Comment by Shubham-koli** [comment]
I think DCO error has been resolved.

**Review by denyeart — APPROVED** [review]

**Review by jyellick — APPROVED** [review]

**Pull request merged**
