### PR TITLE
Update github workflows to ubuntu 22.04

### PR DESCRIPTION
**Pull request by denyeart**
Update github workflows to ubuntu 22.04.

### CODE REVIEW

**Comment by denyeart** [comment]
@ryjones Would we be able to get runners for `fabric-ubuntu-22.04`?

**Comment by ryjones** [comment]
> @ryjones Would we be able to get runners for `fabric-ubuntu-22.04`?

Yes

**Comment by ryjones** [comment]
> > @ryjones Would we be able to get runners for `fabric-ubuntu-22.04`?
> 
> Yes

`fabric-ubuntu-latest` is already 22.04. do you want `fabric-ubuntu-latest` to be 24.04, and a specific runner for 22.04?

**Review by C0rWin — APPROVED** [review]

**Comment by denyeart** [comment]
> > > @ryjones Would we be able to get runners for `fabric-ubuntu-22.04`?
> > 
> > 
> > Yes
> 
> `fabric-ubuntu-latest` is already 22.04. do you want `fabric-ubuntu-latest` to be 24.04, and a specific runner for 22.04?

@ryjones  If `fabric-ubuntu-latest` will remain at 22.04 until we explicitly move up, we can use `fabric-ubuntu-latest`. What I'm trying to avoid is having `fabric-ubuntu-latest` move up without our knowledge and consent. For that reason I thought it would be safer to use `fabric-ubuntu-22.04`. But if `fabric-ubuntu-latest` will stay at 22.04 then we can use it.

**Comment by denyeart** [comment]
Talked to Ry, we're just going to use `fabric-ubuntu-22.04` for the time being.

**Pull request merged**
