### PR TITLE
Update chaincode4noah.rst

### PR DESCRIPTION
**Pull request by magicliang**
## Description

There is a typo in the document. It should have complete '' then it is a legal command.

Signed-off-by:

### CODE REVIEW

**Comment by j143-zz** [comment]
Hi @magicliang , nice fix. But, I believe this is a read only mirror, and contributions can be done [here](https://gerrit.hyperledger.org/r/#/admin/projects/fabric).

**Comment by magicliang** [comment]
I  can understand you are encouraging contributors to use uniform approaches. Can you briefly summarize how many steps if I want to merge this typo fix into master branch?

**Comment by j143-zz** [comment]
It's a very friendly process. :) [this should take a little time]
I believe, you are using `git` (no problem, if you are not)
1. create an id: http://hyperledger-fabric.readthedocs.io/en/latest/Gerrit/lf-account.html#creating-a-linux-foundation-id
2. configure: http://hyperledger-fabric.readthedocs.io/en/latest/Gerrit/lf-account.html#configuring-gerrit-to-use-ssh
3. submitting the change: http://hyperledger-fabric.readthedocs.io/en/latest/Gerrit/changes.html

**Comment by ghost** [comment]
Thank you for your contribution. This is a read only mirror, however. Please [read the guide here](http://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html) for directions on contributing.

**Pull request closed without merging**
