### PR TITLE
fix: modify certificate alternate DNS duplication

### PR DESCRIPTION
**Pull request by zhj0811**
Signed-off-by: zhj0811 <zhaojian@peerfintech.cn>

### CODE REVIEW

**Review by ale-linux — COMMENTED** [review]
Thanks! Could you please provide some more context here - what is the issue? Is there a JIRA?

**Review by sykesm — CHANGES_REQUESTED** [review]
Thanks for the PR.

The change looks correct to me but there  needs to be a corresponding test update. Since the current code isn't working as intended, there's clearly a test gap that needs to be addressed.

`ca_test.go` contains the tests for `SignCeritificate` and I'd expect new assertions around line 230.

**Comment by zhaojianpeerfintech** [comment]
> Thanks! Could you please provide some more context here - what is the issue? Is there a JIRA?

image

It is a tiny PR. The  X509v3 Subject Alternative Name result contains duplicate alternateNames when alternateNames using multi domain

**Comment by zhaojianpeerfintech** [comment]
> Thanks for the PR.
> 
> The change looks correct to me but there needs to be a corresponding test update. Since the current code isn't working as intended, there's clearly a test gap that needs to be addressed.
> 
> `ca_test.go` contains the tests for `SignCeritificate` and I'd expect new assertions around line 230.

The PR does not affect the ca_test.go.  It is negligible.

**Comment by sykesm** [comment]
> > Thanks for the PR.
> 
> > 
> 
> > The change looks correct to me but there needs to be a corresponding test update. Since the current code isn't working as intended, there's clearly a test gap that needs to be addressed.
> 
> > 
> 
> > `ca_test.go` contains the tests for `SignCeritificate` and I'd expect new assertions around line 230.
> 
> 
> 
> The PR does not affect the ca_test.go.  It is negligible.

I'll try to be more clear. The fix is fine but the pull request *must* include a corresponding update to the unit tests to ensure the issue is resolved and is not regressed.

To quote our contribution guidelines:  
> Include unit and integration tests (or changes to existing tests) with every change.

Without a test update, the PR as written will not be merged.

Thanks.

**Review by sykesm — APPROVED** [review]

**Comment by sykesm** [comment]
@Mergifyio backport release-2.2

**Pull request merged**
