### PR TITLE
Rename --channel-id to --channelID in osadmin

### PR DESCRIPTION
**Pull request by jcastrence**
#### Type of change

- Improvement (improvement to code, performance, etc)

#### Description

- Rename --channel-id flag in osadmin to --channelID to match the rest of fabric flags

### CODE REVIEW

**Review by sykesm — DISMISSED** [review]
LGTM.

**Comment by ale-linux** [comment]
thanks for your PR! It looks like you may have missed one spot here

https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=29062&view=logs&j=6b58850f-3858-5a05-33e2-5e41cbf03c4e&t=bddec1cf-ba37-5883-9c3e-fd1e8608f9a1&l=98

**Review by lindluni — APPROVED** [review]

**Comment by pamandrejko** [comment]
@lindluni Can we backport this to relase-2.3? Not sure I have authority to do that?

**Comment by wlahti** [comment]
@Mergifyio backport release-2.3

**Comment by denyeart** [comment]
@sykesm @ale-linux @lindluni Shouldn't a flag change require an associated release note entry? I'm good with the change since it is so soon after the introduction in v2.3.0 release and therefore not many people are using it yet, just want to make sure maintainers identify release note candidates during review. I'm happy to do this one since it already got merged.

**Pull request merged**
