### PR TITLE
Use of invalid path

### PR DESCRIPTION
**Pull request by ronaldpetty**
Hi,

First, love the docs, one of the only projects on Earth that actually really document how to generate offline viewable docs, bravo.

For the local build, it states "starting from the main fabric" directory implies your in the directory; the enumerated steps show otherwise as if your above it.  Updated to assume you are in the directory per the previous statement.

Happy New Year!

## How Has This Been Tested?
Read the docs and can't copy and paste based on how it is written, fix allows that.

## Checklist:
- [x] I have added a [Signed-off-by]
- [x] I have either added documentation to cover my changes or this change requires no new documentation.
- [x] I have either added unit tests to cover my changes or this change requires no new tests.
- [x] I have run [golint](https://github.com/golang/lint) and have fixed valid warnings in code I have added or modified. This tool generates false positives so you may choose to ignore some warnings. The goal is clean, consistent, and readable code.

Signed-off-by: Ronald Petty <ronald.petty@minimumdistance.com>

### CODE REVIEW

**Comment by ronaldpetty** [comment]
Updated checklist.

**Comment by christo4ferris** [comment]
@ronaldpetty Thanks for submitting this change. However, per my previous comment on #91 please submit this change via Gerrit as per the [CONTRIBUTIONS](http://hyperledger-fabric.readthedocs.io/en/master/CONTRIBUTING.html) process. Thanks!

**Comment by ronaldpetty** [comment]
@christo4ferris , yes sorry, I need a better way to make notes of these things.  I will wrap up my mess this weekend and do it the right way!

**Comment by gocuntian** [comment]
image

**Pull request closed without merging**
