### PR TITLE
Update go-kit to v0.10.0

### PR DESCRIPTION
**Pull request by wlahti**
Trying to see if this helps with the statsd flake: [FAB-18038](https://jira.hyperledger.org/browse/FAB-18038l)

### CODE REVIEW

**Comment by wlahti** [comment]
No failures the first time. Let's try it again. :)

**Comment by wlahti** [comment]
Success two times in a row!

**Comment by lindluni** [comment]
At least this flake wasn't because of the metrics provider :)

**Comment by lindluni** [comment]
/azp run

Testing again

**Comment by wlahti** [comment]
Ah, but there it is, which sadly means this is not the fix. I've been trying to investigate the root cause but no luck yet.

**Pull request closed without merging**
