### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by huaweibcs**
Signed-off-by: wuqiaomin <wuqiaomin2@huawei.com>

### CODE REVIEW

**Review by mastersingh24 — APPROVED** [review]
While this file was is actually generated by a script and the actual commit message itself will not be updated, this change should be OK as all additions are prepends anyway.

I'll approve unless anyone else has objections

**Review by denyeart — APPROVED** [review]
There is no need to update the old changelog, but we appreciate the contribution and will merge it!

**Pull request merged**
