### PR TITLE
[FAB-17719] Upgrade docs for 2.1

### PR DESCRIPTION
**Pull request by joealewine**
Change-Id: I20ab394855ddafc50df3713ea17c6c83699867ca
Signed-off-by: joe-alewine <Joe.Alewine@ibm.com>

#### Type of change

- Documentation update

#### Description

Add references for instructions/process for upgrading from 1.4.x to 2.0 as well as from 2.0 to 2.x.

### CODE REVIEW

**Comment by joealewine** [comment]
@Mergifyio backport release-2.1

**Comment by joealewine** [comment]
Please don't merge this until @denyeart reviews it.

**Review by denali49 — COMMENTED** [review]
lgtm

**Review by denyeart — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergifyio backport release-2.1

**Pull request merged**
