### PR TITLE
Fixed typo in commercial_paper.md

### PR DESCRIPTION
**Pull request by karim-ch**
#### Type of change
- Documentation update
#### Description
Fixed redundent 'the' typo

### CODE REVIEW

**Comment by pamandrejko** [comment]
@karim-ch Thank you for fixing this! You need to sign off on the change before we can merge it.

To fix, head to your local branch and run:

git commit --amend --signoff

Now your commits will have your sign off. Next run

git push --force-with-lease origin patch-1

**Comment by karim-ch** [comment]
Hello, I'm getting this error when I type 
`git push --force-with-lease origin patch-1`

> error: src refspec patch-1 does not match any.
> error: failed to push some refs to 'https://github.com/hyperledger/fabric.git'

What shall I do please ?

**Comment by pamandrejko** [comment]
@btl5037 Brett - Can you advise Karim on what he should do here to sign his commit. The instructions from above do not seem to be working in this case.

**Comment by ryjones** [comment]
@pamandrejko @karim-ch needs a valid email address in GitHub.

**Comment by ryjones** [comment]
please see #861

**Pull request closed without merging**
