### PR TITLE
Fix images in network concept and upload new diagrams power point

### PR DESCRIPTION
**Pull request by joealewine**
Images in "How Fabric networks are structured" docs included
R4 when R4 has been replaced with R0. Also, this uploads the
"diagrams" power point folder which contains the raw versions
of these files if they never need to be edited in the future.

Change-Id: I6cd174da823e7b4ec0e348d0a0d388a7219e8f60
Signed-off-by: joe-alewine <Joe.Alewine@ibm.com>

#### Type of change

- Documentation update

#### Description

See above.

### CODE REVIEW

**Comment by joealewine** [comment]
Not sure why these files are empty. Will investigate.

**Comment by joealewine** [comment]
Builds look good to me, so despite the "empty" files, the images seem to be fixed with this PR. 

Screen Shot 2021-02-21 at 9 35 46 PM

**Comment by joealewine** [comment]
Screen Shot 2021-02-21 at 9 35 53 PM

**Review by pamandrejko — APPROVED** [review]

**Comment by joealewine** [comment]
@Mergifyio backport release-2.3

**Comment by pamandrejko** [comment]
@Mergifyio backport release-2.2

**Pull request merged**
