### PR TITLE
Add Throttle to ListOne

### PR DESCRIPTION
**Pull request by lindluni**
The ListOne function queries the Channel Participation API using Gomega Eventually. The default polling interval is 10ms results in many transient http clients being created and on systems with low Open File Limits this results in too many open files. This change adds a one second throttle to the ListOne function.

Signed-off-by: Brett Logan <lindluni@github.com>

### CODE REVIEW

**Comment by lindluni** [comment]
Looking at the log output of the CP API flake, I think this will fix the flake as well, looks like the flake is caused by the endpoint being overwhelmed.

**Comment by sykesm** [comment]
If we need to throttle, can we throttle in the implementation like we've done for sessions instead of at the call site?

Also, the polling probably isn't the file descriptor leak; it's probably the transient creation of two clients each time the function is called that is creating creating a new transport with an associated idle connection pool.

**Comment by lindluni** [comment]
> Also

Yep, its the clients being created thats causing the issue, thats apparent from the log. I'll change the wording of the commit message.

**Comment by lindluni** [comment]
How far should I wire the throttle. Would you rather I expose the `sessionLastExecuted` map on the `Network` object (and rename it to something more agnostic) and make use of that since I have access to the the network object in the `ListOne` function, or should I just create something locally to manage it.

**Comment by lindluni** [comment]
I added it to the network object, if you'd rather I do it locally, I can change it

**Comment by lindluni** [comment]
Decided to do it locally

**Comment by guoger** [comment]
#2412 for similar reason

**Comment by lindluni** [comment]
#2411 resolved the issue this was attempting to fix, thanks @sykesm

**Comment by sykesm** [comment]
I think there's still value in exposing a throttling mechanism on the network. It's worth considering what that would look like.

Is it Network#Eventually(...)?
Is it exposing a throttle object?
Is it exporting what we have as a function with a wait time or channel instead of a map?

Basically, it may have been premature to close this as it solves a problem - just not necessarily the file descriptor one.

**Pull request closed without merging**
