### PR TITLE
Orderer v3: fix IsChannelMember to match public keys (backport #4011)

### PR DESCRIPTION
**Pull request by dviejokfs**
This is a backport of the pull request https://github.com/hyperledger/fabric/pull/4011.

### CODE REVIEW

**Comment by denyeart** [comment]
@dviejokfs Is there a reason the updates to the two test files weren't backported? Even though the tests may not be identical between main and release-2.4 I believe it should be possible to backport the tests.

Also, usually the backport PRs for release-2.5 and release-2.4 are done at the same time so that we don't forget one of them.

**Comment by dviejokfs** [comment]
@denyeart 

`MultiNodeEtcdRaftNoSysChan` is not defined in the release-2.4

There's a big difference between the code related to the Orderer in the `main` branch and the `release-2.4` branch

**Comment by tock-ibm** [comment]
> @denyeart
> 
> `MultiNodeEtcdRaftNoSysChan` is not defined in the release-2.4
> 
> There's a big difference between the code related to the Orderer in the `main` branch and the `release-2.4` branch

@dviejokfs @denyeart 

The bug manifested itself when this testcase was converted to not use the system channel: integration/raft/cft_test.go use-case: "disregards certificate renewal if only the validity period changed"

Since in 2.4 & 2.5 we still support the system channel, what should be done is to add another version of the testcase, but without the system channel. Since 2.4 & 2.5 are lacking some of the support we already implemented into main, that would have to be done ad-hoc for these tests. I can help with this.

**Comment by denyeart** [comment]
Ok, we could either add the test ad-hoc in the back releases, or we could accept the risk given that there are tests in main branch and the code change is the same across branches and fairly simple.

@tock-ibm As the maintainer with most knowledge here, I'll defer to your judgement...

**Comment by tock-ibm** [comment]
@dviejokfs @denyeart 

see: backports with tests
#4071 to release-2.5
#4073 to release-2.4

**Comment by denyeart** [comment]
Ok, closing this one in favor of #4073

**Pull request closed without merging**
