### PR TITLE
Fix typo on terminal command 

### PR DESCRIPTION
**Pull request by marcovoliveira**
#### Type of change
- Bug fix
- Documentation update

#### Description

Fix typo on terminal command

### CODE REVIEW

**Review by denali49 — APPROVED** [review]
lgtm, thanks @marcovoliveira

**Comment by denali49** [comment]
Please sign your commit, thanks!

**Comment by ale-linux** [comment]
@marcovoliveira thx for your contribution, pls follow the steps here

https://github.com/hyperledger/fabric/pull/2989/checks?check_run_id=3937990890

to complete your commit

**Comment by ale-linux** [comment]
Closing because of the long inactivity

**Pull request closed without merging**
