### PR TITLE
Add the sample policy to remove the test warning info

### PR DESCRIPTION
**Pull request by bjzhang03**
Signed-off-by: bjzhang <bjzhang1991@gmail.com>

#### Type of change

- Test update

#### Description

When I run the test, it always tell the warning.
I found the reason and repair it by add the sample policy in it.

### CODE REVIEW

**Comment by bjzhang03** [comment]
warning

**Comment by bjzhang03** [comment]
warning

**Comment by mastersingh24** [comment]
@bjzhang03  - thanks for this change.  I'm ok with backporting this, but this pull request should be made against the master branch as well.

**Review by mastersingh24 — CHANGES_REQUESTED** [review]
As noted in my comment, please make a pull request for this on the master branch as well

**Comment by bjzhang03** [comment]
> @bjzhang03 - thanks for this change. I'm ok with backporting this, but this pull request should be made against the master branch as well.
The master use the different test case, and does not have this problem.

**Comment by bjzhang03** [comment]
The master use the different test case, and does not have this problem.

**Review by mastersingh24 — APPROVED** [review]

**Pull request merged**
