### PR TITLE
Fixed a typo in private_data_tutorial

### PR DESCRIPTION
**Pull request by realnimish**
Signed-off-by: realnimish <realnimish@gmail.com>

#### Type of change

- Documentation update

### CODE REVIEW

**Review by realnimish — COMMENTED** [review]
Signed-off-by: realnimish realnimish@gmail.com

**Review by denali49 — APPROVED** [review]
lgtm, thanks for fixing @realnimish!

**Comment by denali49** [comment]
> Signed-off-by: realnimish [realnimish@gmail.com](mailto:realnimish@gmail.com)

I do not think it caught your sign-off (DCO) the first time.  For instructions on how to fix this, click on the 'Details' link next to the failed DCO line.

**Comment by denyeart** [comment]
@realnimish Do you intend to add your signoff?

**Comment by realnimish** [comment]
Apologies for the delay! I followed the steps from DCO and I'm getting following error message when executing the push command:

remote: Permission to hyperledger/fabric.git denied to realnimish.
fatal: unable to access 'https://github.com/hyperledger/fabric.git/': The requested URL returned error: 403

**Pull request closed without merging**
