### PR TITLE
Add Joe Alewine as a Doc Maintainer

### PR DESCRIPTION
**Pull request by pamandrejko**
Signed-off-by: pama-ibm <pama@ibm.com>

#### Type of change

- Documentation update

#### Description

Joe Alewine is a recognized expert in Fabric as well as Fabric documentation. We'd like to add him as Documentation maintainer.

### CODE REVIEW

**Comment by jmason90** [comment]
Since I started working with Hyperledger Fabric, Joe has been a driver on Fabric documentation quality. Working with maintainers, Joe has documentated many of the more complex features of Fabric very well. As the Fabric software continues to add new features and be refactored, Joe has kept many documentation areas current. He also has provided some of the most important insights on how to restructure and present the documentation to improve it's value to the different audiences that depend on it. For a complex solution stack, the documentation makes it easy for many audiences to consume Fabric productively and Joe has been key to that success.

**Comment by denyeart** [comment]
Our intent has been to split Fabric docs into its own repository after the transition to GitHub and Azure Pipelines. We only have one more repository to switch over (fabric-test), then will proceed with the documentation split.

I'd suggest that we identify the top documentation contributors and reviewers to seed the fabric docs repository maintainer list in the coming weeks (including Joe), rather than pulling the trigger in the Fabric repository this week.

**Review by guoger — DISMISSED** [review]
Much appreciate Joe's work!

**Comment by guoger** [comment]
@denyeart i thought splitting docs was debated and ruled out? this could help our translation group greatly.

**Comment by denyeart** [comment]
> @denyeart i thought splitting docs was debated and ruled out? this could help our translation group greatly.

Deeper discussion ongoing in the mailing list, let's take the discussion there.

**Review by christo4ferris — COMMENTED** [review]
+1

**Review by mastersingh24 — COMMENTED** [review]
I'm good with this based on the contributions and the fact that he'll be focused on the docs.  Would prefer to have people actual do more reviews prior to nomination.

**Comment by lindluni** [comment]
@pamandrejko Remind me in the morning to touch base with you, Jay figured out how to fix the fact that this won't pass CI. We just need to do something small to fix it

**Comment by caod123** [comment]
@pamandrejko can you force push over this branch or rebase on master to retrigger CI? There's a rogue integration test run that's linked to this PR that's marked as failed but is actually passed. We've had some success with getting rid of the rogue CI builds by just rebasing PRs.

**Comment by pamandrejko** [comment]
@caod123 Danny - I added a space to the doc and did a force push. See if that helps?

**Comment by caod123** [comment]
> @caod123 Danny - I added a space to the doc and did a force push. See if that helps?

Looks good thanks! The rogue build disappeared, so this should eventually pass now.

**Comment by ryjones** [comment]
it looks like a) this has stalled b) it has a merge conflict due to my shenanigans. I suggest this is rebased and merged. It doesn't seem like there is much pushback. Also - I suggest either a new section that calls these out functionally. Please alpha order additions.

**Comment by pamandrejko** [comment]
Thanks Ry - we are getting ready to propose a new process for merging documentation-only content into Fabric - so we will either re-use this issue or create a new one. Hope to resolve shortly.

**Comment by denyeart** [comment]
Given the updated direction for doc approvers/maintainers, let's close this one for now, it can always be re-opened if we want to re-use it for some reason.

**Pull request closed without merging**
