### PR TITLE
Add release notes for v3.0.0-beta

### PR DESCRIPTION
**Pull request by denyeart**
Add release notes for v3.0.0-beta.

### CODE REVIEW

**Comment by denyeart** [comment]
@yacovm @tock-ibm ,

Anything else you want mentioned in SmartBFT section of release notes, or in [What's New](https://hyperledger-fabric.readthedocs.io/en/latest/whatsnew.html#byzantine-fault-tolerant-bft-ordering-service), or in the announcement email?

**Comment by yacovm** [comment]
maybe write that the delta from the preview version is the byzantine block pulling?

**Comment by denyeart** [comment]
> maybe write that the delta from the preview version is the byzantine block pulling?

Agreed, go ahead and suggest exact text or make a 2nd commit for this and other details, because your wording will certainly be more accurate than mine!

**Comment by yacovm** [comment]
I tried pushing the commit to your repo but I got access denied, so I added my signed off here: https://github.com/hyperledger/fabric/pull/4751

**Comment by denyeart** [comment]
Ok, the DCO check is sensitive... we have ability to force pass it after confirming the commit is indeed signed, but I'll go ahead and close and we can use your PR.

**Pull request closed without merging**
