### PR TITLE
Update docs for Ed25519 support

### PR DESCRIPTION
**Pull request by denyeart**
Update docs for Ed25519 support.
Also clarify ECDSA and RSA support.

### CODE REVIEW

**Comment by denyeart** [comment]
@johannww @adecaro @ale-linux Please review

**Comment by Jellyman447** [comment]
Approved

**Comment by denyeart** [comment]
@johannww Just to confirm, does your thumbs up mean you've reviewed and approve the doc updates? Or that you intend to review? Once you confirm I think we can merge...

**Comment by johannww** [comment]
@denyeart I will review. I had the impression that it was already merged, that is why I forgot about it.

**Comment by johannww** [comment]
It's good for me. I would say that there is no update for the cryptogen docs. However, I noticed that the cryptogen docs are very generic, and following this principle, there is no reason to highlight it. Besides, the algorithm support is already mentioned on the default config [cmd/cryptogen/main.go line 131](https://github.com/hyperledger/fabric/blob/ea74ec009ab37186a372d3d7a0cc6c0bdd160d0a/cmd/cryptogen/main.go#L131).

**Comment by denyeart** [comment]
> It's good for me. I would say that there is no update for the cryptogen docs. However, I noticed that the cryptogen docs are very generic, and following this principle, there is no reason to highlight it. Besides, the algorithm support is already mentioned on the default config [cmd/cryptogen/main.go line 131](https://github.com/hyperledger/fabric/blob/ea74ec009ab37186a372d3d7a0cc6c0bdd160d0a/cmd/cryptogen/main.go#L131).

Yeah, It looks like for crytpogen there is no doc for the template beyond stating that you can do `cryptogen showtemplate`, and if you do so, the template states that you can specify "ecdsa" or "ed25519", so I think it is fine, I'll go ahead and merge.

**Pull request merged**
