### PR TITLE
Retire Brett Logan as maintainer

### PR DESCRIPTION
**Pull request by lindluni**
It's time, those who are active with the project should maintain it, which is no longer me unfortunately, I wish everyone the best in the future and thank you for everything everyone has done for me.

I've removed my access to all Hyperledger resources.

### CODE REVIEW

**Review by yacovm — APPROVED** [review]

**Review by denyeart — APPROVED** [review]

**Review by manish-sethi — APPROVED** [review]
Sad to see you go @lindluni

**Review by cendhu — APPROVED** [review]
Thanks, Brett, for your contribution.

**Comment by davidkel** [comment]
@lindluni All the best Brett, many thanks for all your help and contribution

**Comment by denyeart** [comment]
I don't think we need majority approval for a self-retirement, I'll go ahead and merge.

**Pull request merged**
