### PR TITLE
Commercial Paper tutorial - corrected Org1 text in Org2 box to Org2

### PR DESCRIPTION
**Pull request by Grant-Steinfeld**
- Documentation update

In docs/source/tutorial/commercial_paper.diagram.testnet.png image updated this image to have the text in Org2 box from the incorrect Org1 box header to Org2

### CODE REVIEW

**Review by ale-linux — COMMENTED** [review]
Thanks for your help! While we're fixing this, I'm wondering whether the "Org1 CA" box in the Ordering Organization box is also correct?

**Comment by Grant-Steinfeld** [comment]
Hi @ale-linux I'll take a look and update this PR soon.

Thanks! 

Grant

> Org1 CA" box in the Ordering Organization box is also correct?

**Comment by Grant-Steinfeld** [comment]
Hi @ale-linux I took a look and yes you were correct, the CA for the Ordering Organization should be part of itself.  I updated the image.  Thanks!

**Review by nikhil550 — APPROVED** [review]
Thanks for this change

**Comment by nikhil550** [comment]
@mergifyio backport release-2.3

**Comment by nikhil550** [comment]
@mergifyio backport release-2.2

**Pull request merged**
