### PR TITLE
Update couchdb_tutorial.rst

### PR DESCRIPTION
**Pull request by rvadym**
#### Description

Typo correction: chainocde  -> chaincode

#### Additional details

-none-

#### Related issues

-none-

### CODE REVIEW

**Review by nikhil550 — APPROVED** [review]
LGTM. Thanks for catching this!

**Comment by nikhil550** [comment]
@rvadym You need to sign your commit in order to merge this PR

You can use this command:`git commit --amend -s` 
and then force push to this pr: `git push origin -f`

**Comment by sykesm** [comment]
Given the age of this PR, I opened https://github.com/hyperledger/fabric/pull/1332 to fix the three occurrences of this typo in the docs.

**Comment by sykesm** [comment]
Thank you for the PR! Fixed in #1332.

**Comment by rvadym** [comment]
@nikhil550 @sykesm 
Sorry for delay, just too many things on my plate atm.
And thank you for taking care about this typo fix!
Good luck!

**Pull request closed without merging**
