### PR TITLE
Update doc to reflect change in FAB-18163

### PR DESCRIPTION
**Pull request by jyellick**
#### Type of change

- Documentation update

#### Description

The original change for FAB-18163 already merged forgot to update the doc.

### CODE REVIEW

**Review by joealewine — APPROVED** [review]
lgtm

**Comment by jyellick** [comment]
@Mergifyio backport release-2.2

**Comment by jyellick** [comment]
@Mergifyio backport release-2.1

**Comment by jyellick** [comment]
@Mergifyio backport release-1.4

**Pull request merged**
