### PR TITLE
Remove ccenv dependency from platforms unit test

### PR DESCRIPTION
**Pull request by wlahti**
The "latest" tag has been retired so it can no longer be pulled for unit tests.

### CODE REVIEW

**Review by lindluni — DISMISSED** [review]

**Comment by sykesm** [comment]
Instead of doing this, why can't we just rid ourselves of the image dependency in the platforms test?

**Comment by sykesm** [comment]
> Instead of doing this, why can't we just rid ourselves of the image dependency in the platforms test?

```diff
diff --git a/core/chaincode/platforms/platforms.go b/core/chaincode/platforms/platforms.go
index cad7c2c65..ddd7b0163 100644
--- a/core/chaincode/platforms/platforms.go
+++ b/core/chaincode/platforms/platforms.go
@@ -49,9 +49,12 @@ func (pw PackageWriterWrapper) Write(name string, payload []byte, tw *tar.Writer
        return pw(name, payload, tw)
 }

+type BuildFunc func(util.DockerBuildOptions, *docker.Client) error
+
 type Registry struct {
        Platforms     map[string]Platform
        PackageWriter PackageWriter
+       DockerBuild   BuildFunc
 }

 var logger = flogging.MustGetLogger("chaincode.platform")
@@ -67,6 +70,7 @@ func NewRegistry(platformTypes ...Platform) *Registry {
        return &Registry{
                Platforms:     platforms,
                PackageWriter: PackageWriterWrapper(writeBytesToPackage),
+               DockerBuild:   util.DockerBuild,
        }
 }

@@ -133,7 +137,7 @@ func (r *Registry) StreamDockerBuild(ccType, path string, codePackage io.Reader,
        buildOptions.InputStream = codePackage
        buildOptions.OutputStream = output

-       err = util.DockerBuild(buildOptions, client)
+       err = r.DockerBuild(buildOptions, client)
        if err != nil {
                return errors.Wrap(err, "docker build failed")
        }
diff --git a/core/chaincode/platforms/platforms_test.go b/core/chaincode/platforms/platforms_test.go
index 1741f67df..14f3c3a18 100644
--- a/core/chaincode/platforms/platforms_test.go
+++ b/core/chaincode/platforms/platforms_test.go
@@ -82,6 +82,7 @@ ENV CORE_CHAINCODE_BUILDLEVEL=%s`, metadata.Version, metadata.Version)
                        tw = tar.NewWriter(buf)
                        pw = &mock.PackageWriter{}
                        registry.PackageWriter = pw
+                       registry.DockerBuild = func(util.DockerBuildOptions, *docker.Client) error { return nil }
                        dockerClient, err := docker.NewClientFromEnv()
                        Expect(err).NotTo(HaveOccurred())
                        client = dockerClient
```

Not pretty but it's targeted and removes another image dependency.

**Review by sykesm — APPROVED** [review]

**Comment by lindluni** [comment]
@Mergifyio backport release-2.2

**Comment by lindluni** [comment]
@Mergifyio backport release-2.1

**Comment by lindluni** [comment]
@Mergifyio backport release-2.0

**Pull request merged**
