### PR TITLE
fix path for make dir CCAAS Builders

### PR DESCRIPTION
**Pull request by pfi79**

### CODE REVIEW

**Comment by yacovm** [comment]
@mbwhite

**Comment by pfi79** [comment]
command "@mkdir -p ../release/$(strip $(platform))/builders/ccaas/bin" creates a directory outside the directory fabric

**Comment by mbwhite** [comment]
@pfi79 thanks for taking the time to submit a PR..

Could you explain when you hit problems please?  As I just tried building the ccaas builders and the directory was created correctly... Here's the steps I did  running `make ccaasbuilder` from the root of the fabric repo


```
➜  fabric git:(main) tree release
release [error opening dir]

0 directories, 0 files
➜  fabric git:(main) make ccaasbuilder
cd ccaas_builder && go test -v ./cmd/detect && GOOS=linux GOARCH=amd64 go build -buildvcs=false -o ../release/linux-amd64/builders/ccaas/bin/ ./cmd/detect/
=== RUN   TestArugments
=== RUN   TestArugments/toofew
=== RUN   TestArugments/twomany
=== RUN   TestArugments/validtype
=== RUN   TestArugments/wrongtype
--- PASS: TestArugments (1.87s)
    --- PASS: TestArugments/toofew (0.01s)
    --- PASS: TestArugments/twomany (0.01s)
    --- PASS: TestArugments/validtype (0.01s)
    --- PASS: TestArugments/wrongtype (0.01s)
=== RUN   TestMissingFile
--- PASS: TestMissingFile (0.27s)
PASS
ok      github.com/hyperledger/fabric/ccaas_builder/cmd/detect  (cached)
cd ccaas_builder && go test -v ./cmd/build && GOOS=linux GOARCH=amd64 go build -buildvcs=false -o ../release/linux-amd64/builders/ccaas/bin/ ./cmd/build/
=== RUN   TestArguements
=== RUN   TestArguements/twomany
=== RUN   TestArguements/toofew1
=== RUN   TestArguements/toofew2
--- PASS: TestArguements (0.43s)
    --- PASS: TestArguements/twomany (0.01s)
    --- PASS: TestArguements/toofew1 (0.01s)
    --- PASS: TestArguements/toofew2 (0.01s)
=== RUN   TestGoodPath
--- PASS: TestGoodPath (0.41s)
=== RUN   TestTemplating
--- PASS: TestTemplating (0.39s)
=== RUN   TestTemplatingFailure
--- PASS: TestTemplatingFailure (0.38s)
=== RUN   TestMissingConnection
--- PASS: TestMissingConnection (0.38s)
=== RUN   TestMissingMetadata
--- PASS: TestMissingMetadata (0.40s)
PASS
ok      github.com/hyperledger/fabric/ccaas_builder/cmd/build   (cached)
cd ccaas_builder && go test -v ./cmd/release && GOOS=linux GOARCH=amd64 go build -buildvcs=false -o ../release/linux-amd64/builders/ccaas/bin/ ./cmd/release/
=== RUN   TestArugments
=== RUN   TestArugments/toofew
=== RUN   TestArugments/twomany
--- PASS: TestArugments (0.39s)
    --- PASS: TestArugments/toofew (0.01s)
    --- PASS: TestArugments/twomany (0.01s)
=== RUN   TestGoodPath
--- PASS: TestGoodPath (0.34s)
=== RUN   TestMissingConnection
--- PASS: TestMissingConnection (0.30s)
PASS
ok      github.com/hyperledger/fabric/ccaas_builder/cmd/release (cached)
➜  fabric git:(main) tree release
release
└── linux-amd64
    └── builders
        └── ccaas
            └── bin
                ├── build
                ├── detect
                └── release

4 directories, 3 files
➜  fabric git:(main)
```

**Comment by pfi79** [comment]
@mbwhite 
> `make ccaasbuilder` from the root of the fabric repo

After the command `make ccaasbuilder`, execute
- `tree release`
- `cd ..`
- `tree release`

**Comment by mbwhite** [comment]
@pfi79 ah  I understand...

good spot!! 

@hyperledger/fabric-core-maintainers I'll add my formal approval, believe this can be merged

**Review by mbwhite — APPROVED** [review]
LGTM

**Review by denyeart — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergifyio backport release-2.5

**Comment by denyeart** [comment]
@Mergifyio backport release-2.4

**Pull request merged**
