### PR TITLE
UpdatePrerequisite.rst

### PR DESCRIPTION
**Pull request by AliakbarETH**
I have updated the line which tells to have docker toolbox as the development prerequisite but on official documentation it's support has been depreciates. Hence, I thought to contribute to help people,

Signed-off-by: Ali Akbar <48174866+BCdeveloper98@users.noreply.github.com>

#### Type of change

- Bug fix
- New feature
- Improvement (improvement to code, performance, etc)
- Test update
- Documentation update

### CODE REVIEW

**Comment by davidkel** [comment]
@BCdeveloper98 The main branch of the docs (which publish to latest and should also be in 2.4) have been completely redone and also includes new documentation for windows users. Could you take a look at that documentation. Unfortunately because the latest documentation has changed a lot the windows section there can't be easily backported and the release-2.2 docs really could use more than just the removal of the Docker Toolbox reference as the recommendation for windows users would be to use WSL2

**Comment by AliakbarETH** [comment]
> @BCdeveloper98 The main branch of the docs (which publish to latest and should also be in 2.4) have been completely redone and also includes new documentation for windows users. Could you take a look at that documentation. Unfortunately because the latest documentation has changed a lot the windows section there can't be easily backported and the release-2.2 docs really could use more than just the removal of the Docker Toolbox reference as the recommendation for windows users would be to use WSL2

Can you please update the official documentation according to the current version? It causes confusion. Regards

**Comment by denyeart** [comment]
I don't know if anybody will update the older release branches... @BCdeveloper98 if you want to update release-2.2 maybe the best thing would be to simply add a note and link on the relevant doc pages that says "for the latest recommendations see the 'latest' version of the docs".

**Comment by AliakbarETH** [comment]
Sure, it seems good to me.

I will definitely do it.

When is release 2.2 coming? On which specific date?

Regards

**Comment by denyeart** [comment]
v2.2.0 has been out almost two years. The latest release on release-2.2 branch is v2.2.5.

**Comment by AliakbarETH** [comment]
Is it LTS ?

I am new to hyper ledger fabric

So finding issues in documentation.

Which one should I work on?

I am basically making a provenance system.

Regards

**Comment by denyeart** [comment]
Yes v2.2 is the current LTS release. We expect v2.5 to become the next LTS release sometime this year.
I'd suggest to work on a doc topic that you find confusing and in need of improvement.

**Comment by denyeart** [comment]
It sounds like this change will not be done. Please open a separate PR for the intended changes.

**Pull request closed without merging**
