### PR TITLE
[FAB-17724] Fix configtxgen cannot find etcdraft default config

### PR DESCRIPTION
**Pull request by DereckLuo**
Signed-off-by: Chongxin Luo <Chongxin.Luo@ibm.com>

#### Type of change

- Bug fix

#### Description
* Fixed configtxgen cannot find etcdraft default config.

#### Related issues
[FAB-17724](https://jira.hyperledger.org/browse/FAB-17724)

### CODE REVIEW

**Review by lehors — APPROVED** [review]
This works. Thanks!

**Comment by denyeart** [comment]
yep, I confirmed as well.

**Review by sykesm — APPROVED** [review]

**Comment by DereckLuo** [comment]
@Mergifyio backport release-2.1

**Comment by denyeart** [comment]
@Mergifyio backport release-2.1

**Comment by denyeart** [comment]
@Mergifyio backport release-2.0

**Pull request merged**
