### PR TITLE
Raft configuration doc issue after mergify backport (release-2.3)

### PR DESCRIPTION
**Pull request by wlahti**
#### Type of change

- Documentation update

#### Description

Something messed up with this mergify doc backport to release-2.3.

### CODE REVIEW

**Review by pamandrejko — APPROVED** [review]
The changes here look good to me. 
I noticed that line 227 in master is different. Assume that is OK?

**Comment by wlahti** [comment]
> The changes here look good to me.
> I noticed that line 227 in master is different. Assume that is OK?

Which line are you referring to? I don't think we have a reason for things to be different in `master` v. `release-2.3` at the moment so maybe something else wasn't backported?

**Review by ale-linux — APPROVED** [review]

**Comment by pamandrejko** [comment]
Release=2.3 and Master content is different:
Screen Shot 2021-01-13 at 8 17 46 AM

**Comment by joealewine** [comment]
@pamandrejko @wlahti Those edits were part of one of my PRs: https://github.com/hyperledger/fabric/commit/b74433561e8ffafd279a46835e27aa9c58b9d01c#diff-0e8aaf7009a56d608fe6e06e4e7963e7093ae35f833be9a4aab4e7dd33d2eaa0

But that should have been backported to 2.3.

**Pull request merged**
