### PR TITLE
Cleanup macOS prerequisites and instructions

### PR DESCRIPTION
**Pull request by sykesm**
Add explicit instructions for macOS and Homebrew.

### CODE REVIEW

**Review by lindluni — APPROVED** [review]

**Comment by btl5037** [comment]
@Mergifyio rebase release-2.1

**Comment by lindluni** [comment]
@Mergifyio backport release-2.1

**Comment by lindluni** [comment]
@Mergifyio backport release-2.0

**Comment by lindluni** [comment]
@Mergifyio backport release-1.4

**Comment by sykesm** [comment]
This should not be pulled back to 1.4.

**Comment by lindluni** [comment]
> This should not be pulled back to 1.4.

Right, I thought about it after I backported. Fortunately they all failed anyway

**Pull request merged**
