### PR TITLE
WIP: prepare for etcd version bump.

### PR DESCRIPTION
**Pull request by guoger**
Signed-off-by: Jay Guo <guojiannan1101@gmail.com>

### CODE REVIEW

**Comment by denyeart** [comment]
Not sure why the /ci-run trigger isn't working, maybe somebody from GitHub would know @lindluni

**Comment by denyeart** [comment]
@guoger Still working on this?

**Comment by guoger** [comment]
> @guoger Still working on this?

sorry for late reply and yes i still have some draft code laying around.

missing pieces are:
- initializing node list when etcdraft instance starts (there's a TODO in code)
- actually bump etcd/raft lib to sane version
- add more UTs

**Comment by Param-S** [comment]
> * initializing node list when etcdraft instance starts (there's a TODO in code)

@guoger If I understand correctly, as per the current implementation, the consenters are set based on the config block when the raft instance gets initialized. I am trying to understand and relate the need for managing the node list in the node struct. Could you help me here to understand.

**Comment by SamYuan1990** [comment]
hi @guoger and all,

what's the progress for this pr?
:-)

**Comment by guoger** [comment]
> hi @guoger and all,
> 
> what's the progress for this pr? :-)

will revive it this week, should be able to update PR in couple of days

**Comment by denyeart** [comment]
@guoger etcd was updated in https://github.com/hyperledger/fabric/pull/2997 , anything else needed for this?

**Comment by denyeart** [comment]
@guoger Reminder...

> @guoger etcd was updated in #2997 , anything else needed for this?

**Comment by denyeart** [comment]
No response from contributor, closing.

**Pull request closed without merging**
