### PR TITLE
Corrected container names in commercial paper tutorial

### PR DESCRIPTION
**Pull request by nidhi-singh02**
Corrected container names in commercial paper tutorial

#### Type of change

- Documentation update

#### Description
Corrected container names in commercial paper tutorial. The container names for Org1 and Org2 were swapped with each other.

Signed-off-by: Nidhi Singh <nidhi2894@gmail.com>

### CODE REVIEW

**Review by nikhil550 — COMMENTED** [review]
The container names are different each time the test network is run. As a result, the container names are just for reference rather than a value that reflects the user experience.

**Comment by nidhi-singh02** [comment]
> The container names are different each time the test network is run. As a result, the container names are just for reference rather than a value that reflects the user experience.

yes, that is there. The container names for peer of Org1 and Org2 are inter-changed in the documentation.

**Comment by denyeart** [comment]
> > The container names are different each time the test network is run. As a result, the container names are just for reference rather than a value that reflects the user experience.
> 
> yes, that is there. The container names for peer of Org1 and Org2 are inter-changed in the documentation.

But you've only updated the container ids in this PR. They are just examples and will be different every time, so not sure how they could be incorrect and require fixing.

**Comment by denyeart** [comment]
BTW, if you do want to proceed with a PR, you'll need to sign the commit, see:
https://github.com/hyperledger/fabric/pull/3088/checks?check_run_id=4380855094

**Comment by denyeart** [comment]
Haven't heard anything for one month, will close for now...

**Pull request closed without merging**
