### PR TITLE
Update app dev tutorial to include Go and Java

### PR DESCRIPTION
**Pull request by bestbeforetoday**
This change uses (linked) tabs to display code snippets and language-specific commands for the user's desired programming language.

In order to use the sphinx-tabs extension, the version of Python used to build the docs had to be updated. Since the `n42org/tox` Docker image used had a very old Python version baked in, and there were no more recent versions available, the `make docs` target now uses the official Python image. In addition to providing a much more current Python environment, this image natively supports arm64 in addition to amd64, allowing docs to be built on Apple Silicon Macs.

### CODE REVIEW

**Comment by bestbeforetoday** [comment]
The tutorial update should also be backported to release-2.5.

**Review by denyeart — APPROVED** [review]
Wow, the new tabs look really good, thank you!

**Comment by denyeart** [comment]
@Mergifyio backport release-2.5

**Comment by denyeart** [comment]
Automatic backport failed due to conflicts...

**Comment by bestbeforetoday** [comment]
Cherry-picked the same change to release-2.5 in PR #5042.

**Pull request merged**
