### PR TITLE
WIP: Throttle concurrent ledger access

### PR DESCRIPTION
**Pull request by wenjianqiao**
Signed-off-by: Wenjian Qiao <wenjianq@gmail.com>

#### Type of change
- Improvement (throttle concurrent ledger access)

#### Description

Add throttle to limit concurrent ledger access

#### Release Note
TBD

### CODE REVIEW

**Comment by kchristidis** [comment]
Oh my goodness, I think I kept bumping into this these past few weeks. (I'm working on a side project.)

In my stress tests I would inevitably bump into this:

`block-notifier:1000 • cannot get block 7166's size: QueryBlock failed: Transaction processing for endorser [localhost:7051]: Chaincode status Code: (500) UNKNOWN. Description: Failed to get block number 7166, error Error getting envelope(proto: can't skip unknown wire type 6 for common.Envelope)`

or, say this:

`block-notifier:2000 • cannot get block 3963's size: QueryBlock failed: Transaction processing for endorser [localhost:7051]: Chaincode status Code: (500) UNKNOWN. Description: Failed to get block number 3963, error Error getting envelope(proto: common.Envelope: wiretype end group for non-group)`

...and my experiments would fail.

I want to review the linked JIRA for more context, but I'm restricted from accessing it. Who controls the access bit?

**Comment by ryjones** [comment]
@kchristidis I've asked on the JIRA if the security bit really needs to be set, or if open access is OK.

**Comment by kchristidis** [comment]
@ryjones: Thanks! A related question: why cannot maintainers see all JIRAs for the project by default?

**Comment by mastersingh24** [comment]
> @ryjones: Thanks! A related question: why cannot maintainers see all JIRAs for the project by default?

Not all maintainers are part of the small group used to assess/triage potential security issues

**Comment by wenjianqiao** [comment]
Close the PR due to design change.

**Pull request closed without merging**
