### PR TITLE
Transfer leadership before submitting to raft library (backport #3651)

### PR DESCRIPTION
**Pull request by Param-S**
#### Type of change
- Improvement (improvement to code)

#### Description
Backport #3651 changes wrt leadership transfer

Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>
Signed-off-by: Yacov Manevich <yacovm@il.ibm.com>
Co-authored-by: Yacov Manevich <yacovm@il.ibm.com>

### CODE REVIEW

**Comment by yacovm** [comment]
why backport to 2.4 ? this is not a bug fix.

**Comment by denyeart** [comment]
> why backport to 2.4 ? this is not a bug fix.

@yacovm  I asked Param to backport to release-2.4 because my CI failure rate was close to 100% due to etcdraft failures in release-2.4, hindering ability to backport other fixes. Does this look good to you?

**Comment by yacovm** [comment]
> > why backport to 2.4 ? this is not a bug fix.
> 
> @yacovm I asked Param to backport to release-2.4 because my CI failure rate was close to 100% due to etcdraft failures in release-2.4, hindering ability to backport other fixes. Does this look good to you?

Do you not find it weird that without backporting an improvement that changes behavior of production code in a corner case, unit tests that although were always flaky, now never pass? What changed?

**Comment by denyeart** [comment]
> > > why backport to 2.4 ? this is not a bug fix.
> > 
> > 
> > @yacovm I asked Param to backport to release-2.4 because my CI failure rate was close to 100% due to etcdraft failures in release-2.4, hindering ability to backport other fixes. Does this look good to you?
> 
> Do you not find it weird that without backporting an improvement that changes behavior of production code in a corner case, unit tests that although were always flaky, now never pass? What changed?

The etcdraft unit test flakes got MUCH worse when we shifted to Github Actions, must be some slightly different timing due to runner differences.

**Review by yacovm — APPROVED** [review]

**Pull request merged**
