### PR TITLE
Update chaincode lifecycle topic

### PR DESCRIPTION
**Pull request by nikhil550**
Signed-off-by: NIKHIL E GUPTA <negupta@us.ibm.com>

#### Type of change

- Documentation update

#### Description

Based on testing and feedback from @jyellick, we will remove the recommendation that users can run chaincode in different languages from the cc lifecycle topic. The barriers to getting it to work are high enough to work that it should not be a practice that we steer folks towards

### CODE REVIEW

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.1

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.0

**Review by denali49 — APPROVED** [review]
lgtm

**Review by pamandrejko — APPROVED** [review]
Thanks Nik

**Comment by pamandrejko** [comment]
@Mergifyio backport release-2.0

**Pull request merged**
