### PR TITLE
Remove global-level endpoints from channel config - mid version - w.i.p.

### PR DESCRIPTION
**Pull request by MayRosenbaum**
#### Type of change

config update

#### Description

This PR aims to block the option to specify global-level endpoints and enforce that endpoints per org are defined.
Integration tests + unit tests were updated.

### CODE REVIEW

**Comment by denyeart** [comment]
@mergifyio rebase

**Comment by yacovm** [comment]
@MayRosenbaum which one is the relevant one? This one or https://github.com/hyperledger/fabric/pull/4778 ? Please close the other one.

**Comment by denyeart** [comment]
Sorry, this now conflicts with the recent commit - https://github.com/hyperledger/fabric/commit/fd3bd582cd3afaddff92ba84d24d327dbb23ce89

**Comment by denyeart** [comment]
@tock-ibm @MayRosenbaum this one should be closed in favor of https://github.com/hyperledger/fabric/pull/4879 right?

**Comment by tock-ibm** [comment]
continued in https://github.com/hyperledger/fabric/pull/4879

**Pull request closed without merging**
