### PR TITLE
Nominate Will Lahti as Fabric Maintainer

### PR DESCRIPTION
**Pull request by sykesm**
Will has been a core contributor to Hyperledger Fabric since 2016. His contributions have been part of the CLI, peer event hub, channel event services, operations, integration tests, metrics, lifecycle 2.0, external chaincode builder, and, more recently, the channel participation API.

Beyond his code contributions, Will works to actively support Fabric users by engaging in discussions on Rocket Chat where he has answered many questions. He also partners effectively with the documentation maintainers to ensure features can be adopted and used by users.

In support of Fabric contributors, Will frequently reviews Fabric pull requests and provides excellent feedback and support that results in improved quality and maintainability.

Will's influence has grown tremendously since his early involvement with Fabric. Given the depth and breadth of Will's contributions, I believe Will is well suited to be a Fabric Maintainer.

### CODE REVIEW

**Review by denyeart — APPROVED** [review]
Well deserved!

**Review by cendhu — APPROVED** [review]

**Review by lindluni — APPROVED** [review]

**Comment by lindluni** [comment]
Long overdue!

**Review by ale-linux — APPROVED** [review]
Well deserved!

**Review by yacovm — APPROVED** [review]
LGTM

**Review by caod123 — APPROVED** [review]

**Review by manish-sethi — APPROVED** [review]

**Comment by denyeart** [comment]
Majority have approved, merging. Congratulations Will!

**Pull request merged**
