### PR TITLE
Release v1.4.11 commit

### PR DESCRIPTION
**Pull request by denyeart**
Final commit for v1.4.11 including doc, script, and release note updates.

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

### CODE REVIEW

**Review by lindluni — DISMISSED** [review]

**Comment by denyeart** [comment]
We are doing some final tests on v1.4.11, let's hold off merging for a few days...

**Comment by lindluni** [comment]
I changed it to draft for now so it can't be merged

**Review by mastersingh24 — DISMISSED** [review]

**Review by lindluni — APPROVED** [review]
What's here looks good, but I didn't take a look at anything that might have been missed.

**Comment by denyeart** [comment]
I compared against prior release commits, we're ready to go, merging.

**Pull request merged**
