### PR TITLE
Deploy a chaincode to new channel command issue

### PR DESCRIPTION
**Pull request by senthilkumar-ofs**
Since the document mentioned chaincode name argument key is --ccn but it should be -ccn.

#### Type of change

- Bug fix
- New feature
- Improvement (improvement to code, performance, etc)
- Test update
- Documentation update

### CODE REVIEW

**Review by denali49 — CHANGES_REQUESTED** [review]
Hello Senthil, thank you for your contribution!  Please note that Developer Certificate of Origin (DCO) sign-off is required on all pull requests (PRs).  If you are on a Windows machine, here is a resource to help you get it set up correctly in git.  https://wiki.hyperledger.org/display/CA/Use+GitHub+for+Windows+and+VSCode
Otherwise, just us the `-s` flag in your git commit command to sign your commits.  Like this:
`git commit -s`.  Thanks for catching this in the docs, we can get your PR merged as soon as you add your DCO to your commit.

**Comment by senthilkumar-ofs** [comment]
> Hello Senthil, thank you for your contribution! Please note that Developer Certificate of Origin (DCO) sign-off is required on all pull requests (PRs). If you are on a Windows machine, here is a resource to help you get it set up correctly in git. https://wiki.hyperledger.org/display/CA/Use+GitHub+for+Windows+and+VSCode
> Otherwise, just us the `-s` flag in your git commit command to sign your commits. Like this:
> `git commit -s`. Thanks for catching this in the docs, we can get your PR merged as soon as you add your DCO to your commit.

i have updated

**Review by denali49 — APPROVED** [review]
lgtm.  Congratulations on being a Fabric contributor Senthil!  Thank you for your contribution!

**Review by denyeart — APPROVED** [review]

**Comment by denyeart** [comment]
I confirmed there are no occurrences in main branch, so just the release-2.2 PR is needed. Thanks Senthil!

**Pull request merged**
