### PR TITLE
[FAB-17405]: Lifecycle CLI omits empty arrays from JSON output

### PR DESCRIPTION
**Pull request by wuxuer**
Description

When either "peer lifecycle chaincode queryinstalled -O json" or "peer
lifecycle chaincode querycommitted -O json" are called, they output a
JSON object that contains the results of the query. If the peer has no
installed or committed chaincodes, the array is also included in the
JSON.

Related issues

https://jira.hyperledger.org/browse/FAB-17405

Signed-off-by: xu wu <wuxu1103@163.com>

#### Type of change

- Improvement (improvement to code)

### CODE REVIEW

**Review by sykesm — CHANGES_REQUESTED** [review]
This needs further discussion. In fact, there isn't really agreement that the issue is really an issue at the moment.

Beyond that, the fix approach is very cumbersome. The tests also don't make use of the appropriate matchers.

**Comment by wuxuer** [comment]
> This needs further discussion. In fact, there isn't really agreement that the issue is really an issue at the moment.
> 
> Beyond that, the fix approach is very cumbersome. The tests also don't make use of the appropriate matchers.

OK, thx. Then I close the PR now. 
If the issueis identified, consider submitting it at that time.

**Comment by sykesm** [comment]
> OK, thx. Then I close the PR now.
> If the issueis identified, consider submitting it at that time.

While I didn't say it earlier, thank you for jumping in on this. Your effort is appreciated.

**Comment by wuxuer** [comment]
> The tests also don't make use of the appropriate matchers.

And I have some doubts about your this proposal. 
Should I write a test function for function printResponseAsJSON instead of function Query, which calls function printResponseAsJSON?
Looking forward to your reply. Thank you!

**Pull request closed without merging**
