### PR TITLE
Bump Go to 1.17.5

### LINKED ISSUE #3073: Update Go to 1.17.x
Update Go to 1.17.x in fabric and related repositories.

Prep PRs:
Fix build tags for Go 1.17 - https://github.com/hyperledger/fabric/pull/3070
Resolve Go 1.17 staticcheck issues for dependency projects - https://github.com/hyperledger/fabric/pull/3114

### PR DESCRIPTION
**Pull request by denyeart**
Bump Go to 1.17.5.
Fix unit tests to work with Go 1.17.5.
Update dependencies to work with Go 1.17.

Resolves #3073 

Signed-off-by: David Enyeart enyeart@us.ibm.com

### CODE REVIEW

**Review by yacovm — DISMISSED** [review]

**Review by ale-linux — CHANGES_REQUESTED** [review]
Tests pass now after bumping the dependencies. Note that we can't merge yet because we're using an untagged version of gnark-crypto

https://github.com/IBM/mathlib/blob/go1.17/go.mod#L6

We have a few options:

1. wait till gnark-crypto cuts their release (the maintainer said it would be a matter of a few days)
2. stick with the untagged version (I wouldn't recommend this)

@denyeart: your call

**Comment by ale-linux** [comment]
See https://github.com/ConsenSys/gnark-crypto/pull/112/#issuecomment-994026674

**Comment by denyeart** [comment]
Thanks @ale-linux , let's wait for their release, converting this PR to Draft.

**Comment by denyeart** [comment]
@ale-linux Happy New Year!
ConsenSys/gnark-crypto v0.6.0 is now released with the fix. Can you update your idemix dependencies to use it, and then update the Fabric idemix dependencies?

**Comment by denyeart** [comment]
Ale's commit resolves the final dependency issue with Go 1.17.
This one is ready for final review now.

**Review by ale-linux — APPROVED** [review]

**Comment by ale-linux** [comment]
LGTM - but I contributed so I won't merge it

**Pull request merged**
