### PR TITLE
Add Security Model topic to docs

### PR DESCRIPTION
**Pull request by denyeart**
Add Security Model topic to docs as a one-stop overview of Fabric security model.

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

### CODE REVIEW

**Review by mastersingh24 — APPROVED** [review]

**Comment by nikhil550** [comment]
@denyeart any objections to backporting to 2.3 and 2.2?

**Comment by nikhil550** [comment]
@mergifiyio backport release-2.3

**Comment by nikhil550** [comment]
@mergifiyio backport release-2.2

**Comment by denyeart** [comment]
Thanks @nikhil550 !

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.3

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.2

**Pull request merged**
