### PR TITLE
add basic issue template/links

### PR DESCRIPTION
**Pull request by ghost**
#### Type of change

- Documentation update

re #4143

#### Description

Strangely, when I'm testing this on my work-fork, I go the bug-template and your vulnerability handling:

https://github.com/abebeos/fabric/issues/new/choose

No idea why, possibly once you merge to your repo this will behave as it should.

(nothing wrong to have the `Report vulnerability`, but it should not appear magically)

### CODE REVIEW

**Comment by denyeart** [comment]
Thank you for the new issue template.

To get past the DCO failure, [please sign the commit](https://github.com/hyperledger/fabric/pull/4144/checks?check_run_id=12483890977).

To get past the Basic Checks, either add a license header at the top of the new files or add the .github directory to the [excluded_files list](https://github.com/hyperledger/fabric/pull/4144/checks?check_run_id=12483890977) (the latter probably makes more sense).

I think the two important issue categories are "Bug Report" which you have, and "Proposed Work Item". Could you add the latter? It could go to a blank entry.

**Comment by ghost** [comment]
> I think the two important issue categories are "Bug Report" which you have, and "Proposed Work Item". Could you add the latter? It could go to a blank entry.

Please refer to https://github.com/hyperledger/fabric/issues/4143#issuecomment-1494887319

(I would prefer that we merge this here to see how it works, and it can be extended afterwards easily)

**Review by denyeart — APPROVED** [review]

**Comment by denyeart** [comment]
Ok @abebeos I've merged it, I also see the "Report a security vulnerability" button.

It looks like github presents it automatically, see https://github.com/orgs/community/discussions/45567, although it may only be visible for the repo administrators. Do you see the option?

**Comment by ghost** [comment]
Yes, though

> This submission will only be viewable to repository maintainers. 

So it seems all is good.

**Pull request merged**
