### PR TITLE
Nominate Fedor Partanskiy (@pfi) to the maintainer

### PR DESCRIPTION
**Pull request by C0rWin**
@pfi has demonstrated a very active contribution over the past year, assisting with code review, fixing and providing patches, maintaining unit tests, and aiding in reducing the number of flakes. Was actively aligning the project with up-to-date libraries and go eco-system updates.

In addition to their technical contributions, Fedor has shown a clear commitment to the project’s success and growth. He has taken the initiative to address issues promptly and has actively participated in discussions to maintain the project’s direction. His consistent effort and dedication make him well-suited for the responsibilities of a maintainer, ensuring the project’s continued success and reliability.

### CODE REVIEW

**Review by denyeart — DISMISSED** [review]
Fedor has been the top contributor to Fabric this year, several of the commits have resolved problems that have stumped many other developers. I look forward to working with Fedor as a maintainer.

**Comment by pfi79** [comment]
@C0rWin
Thank you for the nomination.

Please rename "pfi" to "pfi79".

**Review by manish-sethi — DISMISSED** [review]

**Comment by C0rWin** [comment]
@manish-sethi, @denyeart can you please re-approve? I fixed a typo, Fedor's nickname, per his request.

**Review by yacovm — APPROVED** [review]
Thanks for keeping the home fires burning

**Review by denyeart — APPROVED** [review]

**Review by manish-sethi — APPROVED** [review]

**Comment by C0rWin** [comment]
Given we have a majority vote, I am merging the PR. Congratulations @pfi79 and keep doing a good work :)

**Comment by tock-ibm** [comment]
@pfi79 Welcome!

**Comment by C0rWin** [comment]
@ryjones, can you please help to provide @pfi79 with the necessary permissions?

**Comment by ryjones** [comment]
@C0rWin please file [a pr here](https://github.com/hyperledger/governance/blob/main/access-control.yaml)

**Comment by denyeart** [comment]
@C0rWin @ryjones I've PRed at https://github.com/hyperledger/governance/pull/364

**Comment by denyeart** [comment]
@pfi79 You've been added to fabric-core-maintainers, you should have merge privilege now.

**Comment by pfi79** [comment]
@C0rWin @denyeart @tock-ibm @ryjones @manish-sethi @yacovm 
Thank you so much for adding to the maintainers.
I will be happy to further develop fabric.
There are a lot of plans and ideas.

**Pull request merged**
