### PR TITLE
FAB-16355 Add V2_0_COUCHDB_VALIDATION app capability

### PR DESCRIPTION
**Pull request by wenjianqiao**
Signed-off-by: Wenjian Qiao <wenjianq@gmail.com>

#### Type of change
Feature

#### Description

This PR adds a new channel app capability V2_0_COUCHDB_VALIDATION to 
enforce couchdb requirements on statedb keys/values. 

When this capability is enabled, tx simulator will call statecouchdb.ValidateKeyValue 
to validate that statedb keys/values meets couchdb requirements during endorsement phase. 

Update ledgermgmt, kv_ledger_provider, kv_ledger, txmgr, txsimulator
to take an application config retriever to retrieve the capability.

#### Related issues
FAB-17163

#### Release Note
Document and release note will be added in a separate PR.

### CODE REVIEW

**Review by wenjianqiao — COMMENTED** [review]
/azp run

**Review by jyellick — CHANGES_REQUESTED** [review]
Although the changeset itself looks pretty good, I'm not entirely convinced as to the approach.  Will comment a bit on the JIRA.

**Comment by jyellick** [comment]
Per the comments in the JIRA, we should fix the name before merging.

**Comment by wenjianqiao** [comment]
@jyellick, thanks for your comments. This PR is on hold for now. I will update the capability name if we all agree with the app capability approach. 

@manish-sethi has concerns about supporting both leveldb and couchdb on the same channel. He will comment on the jira ticket FAB-16355.

**Comment by denyeart** [comment]
I commented in FAB-16355 that this is on hold, I think we can close for now and re-open if and when we return to the Jira.

**Pull request closed without merging**
