### PR TITLE
Update "master" branch references to "main". (backport #2495)

### PR DESCRIPTION
**Pull request by WaleedMortaja**
A backport of pull request #2495 ~with some extra edits in a separate commit.~

### CODE REVIEW

**Comment by denyeart** [comment]
@WaleedMortaja Thanks for backporting to release-2.2! It looks good to me... are you still working on additional edits?

**Comment by WaleedMortaja** [comment]
> @WaleedMortaja Thanks for backporting to release-2.2! It looks good to me... are you still working on additional edits?

Yes. I would like to customize the backport for branch `release-2.2` instead of `main`.
Since you are here, would suggest the additional edits be on a separate PR?

**Comment by denyeart** [comment]
I'm actually not seeing a need to reference release-2.2 everywhere. Shifting from master to main was the main objective and it looks like that is done here. If you think a subset of the references should be to release-2.2, then yes open a separate PR for that and we can discuss there.

**Comment by WaleedMortaja** [comment]
Thank you so much.
Then I think this PR is ready to merge.

**Review by denyeart — APPROVED** [review]

**Pull request merged**
