### PR TITLE
fix nodes panic during synchronization

### PR DESCRIPTION
**Pull request by pfi79**
https://github.com/hyperledger/fabric/issues/5076

**What's going on?**

During synchronisation, the synchroniser reads blocks from another node and [writes](https://github.com/hyperledger/fabric/blob/main/orderer/consensus/smartbft/synchronizer_bft.go#L261) them to itself.
Block [writes](https://github.com/hyperledger/fabric/blob/main/orderer/common/multichannel/blockwriter.go#L166) are started asynchronously, and we have no control over when this goroutine will actually be executed. 
Without waiting for the block to be written, the synchroniser proceeds to the next step.
When finished, the synchroniser exits and the code immediately detects that the node has not reached altitude and enters a new synchronisation cycle.

The `startHeight := s.Support.Height()` method is executed as the start of the range to synchronise. But it happens that the previous block has not been written yet (but will be soon) and we choose the number of the block that is about to be written as the start. Thus it is possible to write two identical blocks in a row.

**Proposal** 
Set block recording to synchronous mode

### CODE REVIEW

**Comment by yacovm** [comment]
Thanks for looking into this.

1. What about a unit test that reproduces the problem?
2. I don't understand why we need such a complex solution, when we can just [write the blocks synchronously](https://github.com/hyperledger/fabric/blob/main/orderer/common/multichannel/blockwriter.go#L182)?

**Comment by pfi79** [comment]
> 2\. I don't understand why we need such a complex solution, when we can just [write the blocks synchronously](https://github.com/hyperledger/fabric/blob/main/orderer/common/multichannel/blockwriter.go#L182)?

I was thinking about synchronous writing, but as I think the idea here was to parallele getting the next block from puller and writing the current one to state. That is a time saver.
But if other maintainers agree to convert to synchronous recording, I will.

**Comment by pfi79** [comment]
> 1. What about a unit test that reproduces the problem?

I'm at work on a test. 
Was the first to throw a pr with changes to get corrected right away.

**Comment by yacovm** [comment]
> > 2. I don't understand why we need such a complex solution, when we can just [write the blocks synchronously](https://github.com/hyperledger/fabric/blob/main/orderer/common/multichannel/blockwriter.go#L182)?
> 
> I was thinking about synchronous writing, but as I think the idea here was to parallele getting the next block from puller and writing the current one to state. That is a time saver. But if other maintainers agree to convert to synchronous recording, I will.

we do get the next block from the remote node though, whether you are doing a sync write or an async one.

Because when you [retrieve](https://github.com/hyperledger/fabric/blob/main/orderer/consensus/smartbft/sync_buffer.go#L46) a block from the sync buffer, a new block is [fed](https://github.com/hyperledger/fabric/blob/main/orderer/consensus/smartbft/sync_buffer.go#L39) into it.

**Comment by pfi79** [comment]
> we do get the next block from the remote node though, whether you are doing a sync write or an async one.
> 
> Because when you [retrieve](https://github.com/hyperledger/fabric/blob/main/orderer/consensus/smartbft/sync_buffer.go#L46) a block from the sync buffer, a new block is [fed](https://github.com/hyperledger/fabric/blob/main/orderer/consensus/smartbft/sync_buffer.go#L39) into it.

That's right. I'll redo it.

**Review by yacovm — APPROVED** [review]

**Comment by yacovm** [comment]
I know that you didn't provide a test, but I am perfectly fine with using the sync block writing when we synchronize.

**Pull request merged**
