### PR TITLE
Create structure Doc for Brazilian Portuguese

### PR DESCRIPTION
**Pull request by EvertonMelo**
Bem vindo ao Hyperledger Fabric
=============================

O Hyperledger Fabric e uma plataforma para soluções de ledger distribuidas,
por uma arquitetura modular que oferece altos níveis de confidencialidade, resiliência,
flexibilidade e escalabilidade. Ele é projetado para suportar implementações conectáveis
de diferentes componentes e acomodar a complexidade e os meandros que existem
através do ecossistema enxuto.

O Hyperledger Fabric oferece uma arquitetura flexivel e extensível exclusiva
distinguindo de solucoes alternativas de blockchain. Planejamento para o
O futuro do blockchain corporativo requer a construcao de uma 
arquitetura de código aberto. Hyperledger Fabric é o seu ponto de partida.

E recomendado para usuarios iniciantes começarem a passar por
:doc:`getting_started` secao para ganhar familiaridade com o Hyperledger Fabric
componentes e o fluxo de transação básica.  Uma vez confortavel, continue
Explorando a biblioteca para demonstrações, especificaçoes técnicas, APIs, etc.

.. note:: Se você tiver duvidas nao abordadas por esta documentação, ou se deparar com
           problemas com qualquer um dos tutoriais, visite o :doc:`questions`
          página para algumas dicas sobre onde encontrar ajuda adicional.

Antes de mergulhar, observe como o Hyperledger Fabric está criando um Blockchain para
o seu negocio:

.. raw:: html

   <iframe width="560" height="315" src="https://www.youtube.com/embed/EKa5Gh9whgU" frameborder="0" allowfullscreen></iframe>
   <br/><br/>

.. toctree::
   :maxdepth: 1
   :caption: Table of Contents

   index
   Começando
   Palavras_chave
   tutoriais
   ops_guia
   referencia_de_comandos
   aquitetura
   Fabric-FAQ
   ordering-service-faq
   CONTRIBUINDO
   glossario
   releases
   questoes
   status

.. Licensed under Creative Commons Attribution 4.0 International License
   https://creativecommons.org/licenses/by/4.0/

### CODE REVIEW

**Comment by mastersingh24** [comment]
Ola Everton.  Benvindo ao Fabric.  Obrigado por contribuir com a documentacao.
Nao usamos Github para enviar solicitacoes.  Usamos Gerrit e JIRA.  Olha esta [pagina].(http://hyperledger-fabric.readthedocs.io/en/release-1.1/CONTRIBUTING.html)
Hay um grupo que concentra na documentacao and tambem um canal em [RocketChat](https://chat.hyperledger.org/channel/fabric-documentation).

**Comment by ryjones** [comment]
Thanks for the contribution! this is a read-only mirror. please read the [contribution guide](http://hyperledger-fabric.readthedocs.io/en/release-1.1/CONTRIBUTING.html).

**Comment by EvertonMelo** [comment]
@mastersingh24 @ryjones 

thanks for feedback.

but unfortunately you reacted as expected. 

**1 -** @ryjones no item you sent speaks about translate documentation. 
font: https://github.com/hyperledger/fabric/edit/release-1.1/docs/source/CONTRIBUTING.rst 

or if you prefer in the black JIRA box:
https://jira.hyperledger.org/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all&contains=translate
return 0 itens

**2 -** @mastersingh24 thank you for trying to speak Portuguese.
but Jire or Gerrit, only IBM members are accept.

see it:
https://gerrit.hyperledger.org/r/#/q/translate 
( 11 itens, only Members IBM start PR and Commit ) 
does not contain anything about translations into other languages. 

RocketChat is not documentation, Sorry. 
out that this goes against the [license](https://github.com/hyperledger/fabric/blob/release-1.1/LICENSE) to use.

>       **_"Contribution"_** shall mean any work of authorship, including
>       the original version of the Work and any modifications or additions
>       to that Work or Derivative Works thereof, that is intentionally
>       submitted to Licensor for inclusion in the Work by the copyright owner
>       or by an individual or Legal Entity authorized to submit on behalf of
>       the copyright owner. For the purposes of this definition, "submitted"
>       means any form of electronic, verbal, or written communication sent
>       to the Licensor or its representatives, including but not limited to
>       communication on electronic mailing lists, source code control systems,
>       and issue tracking systems that are managed by, or on behalf of, the
>       Licensor for the purpose of discussing and improving the Work, _**but
>       excluding communication that is conspicuously marked or otherwise
>       designated in writing by the copyright**_ owner as "Not a Contribution."
> 

watch out for companies, 

Conclusion. 
The "HL Fabric" Repository have 2 years of live, there is no policy on translation, nor for suggestion, so I'm sure you do not want it right?

**Comment by mastersingh24** [comment]
@EvertonMelo  - actually, you only need to a Linux Foundation ID in order to use Gerrit, JIRA or even RocketChat.  There is an active documentation working group and I was suggesting using the RocketChat channel to let the folks there know that you are interested in translating the docs to Portuguese.  Feel free to reach out to me directly with any questions.  We are definitely interested in all contributions and translation is a great place to start

**Comment by EvertonMelo** [comment]
@mastersingh24 
I already translated a page and my work was thrown away.

"We just got that way .."
(there is no translation policy)

you can have 1000 translation groups, where are the jobs they do?

send me the link please

[or expose to them what they should do.](https://github.com/hyperledger/fabric/pull/129/commits/e30fd6583c696ae5743e141cb0e7c2c76b2884c9)

since they are leaning on projects doing NOTHING.

**Comment by mastersingh24** [comment]
We only use Github as a read-only clone of our Gerrit repository.  We actually cannot accept PRs via Github.   Change requests can only be merged if they come in via Gerrit.  Here's the [link](http://hyperledger-fabric.readthedocs.io/en/release-1.1/Gerrit/lf-account.html) to getting setup with a Linux Foundation ID and getting started with Gerrit.

**Comment by EvertonMelo** [comment]
hypocrite

**Comment by EvertonMelo** [comment]
@mastersingh24 

"Access denied
You are not authorized to access this page."

thank you.

**Pull request closed without merging**
