### PR TITLE
Fix typo on duplicated word

### PR DESCRIPTION
**Pull request by marcovoliveira**
#### Type of change

- Documentation update

#### Description

Remove duplicated word on documentation

### CODE REVIEW

**Review by ale-linux — DISMISSED** [review]

**Comment by ale-linux** [comment]
Thanks for your contribution - please follow these instructions

https://github.com/hyperledger/fabric/pull/2519/checks?check_run_id=2215424073

to add a sign-off to your commit.

**Comment by mastersingh24** [comment]
@marcovoliveira  - you will need to sign-off on your commit.  See https://github.com/hyperledger/fabric/pull/2519/checks?check_run_id=2215424073

**Review by denyeart — APPROVED** [review]

**Comment by nikhil550** [comment]
@mergifyio backport release-2.3

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.2

**Pull request merged**
