### PR TITLE
Restrict WAL usage to node.go

### PR DESCRIPTION
**Pull request by yacovm**
See https://github.com/hyperledger/fabric/issues/4199

### CODE REVIEW

**Comment by denyeart** [comment]
@tock-ibm Could you review this one?  We'll want to backport it to release-2.5 as well.

**Comment by tock-ibm** [comment]
> @tock-ibm Could you review this one? We'll want to backport it to release-2.5 as well.

I will do it

**Comment by tock-ibm** [comment]
Is there a way to add a test case (unit, or integration) that will trigger the problem? 
Such that we'll know its failing in the existing code and fixed after this PR?

@yacovm @vodsej any suggestions?

**Comment by yacovm** [comment]
> Is there a way to add a test case (unit, or integration) that will trigger the problem? Such that we'll know its failing in the existing code and fixed after this PR?
> 
> @yacovm @vodsej any suggestions?

You want to add a test that attempts to make the Raft chain deadlock? Usually unit tests are written to test a specific functional scenario such that if the implementation changes, the functional scenario still works as expected.

I'm not sure what's the point in writing a test that attempts to deadlock the two goroutines if the fix is to move the WAL sync to a single goroutine as was in the past.

I think it's possible to write such a test since the raft.Node is an interface and can be mocked, but do you not agree with the report that the deadlock may indeed occur?

**Comment by tock-ibm** [comment]
> > Is there a way to add a test case (unit, or integration) that will trigger the problem? Such that we'll know its failing in the existing code and fixed after this PR?
> > @yacovm @vodsej any suggestions?
> 
> You want to add a test that attempts to make the Raft chain deadlock? Usually unit tests are written to test a specific functional scenario such that if the implementation changes, the functional scenario still works as expected.
> 
> I'm not sure what's the point in writing a test that attempts to deadlock the two goroutines if the fix is to move the WAL sync to a single goroutine as was in the past.
> 
> I think it's possible to write such a test since the raft.Node is an interface and can be mocked, but do you not agree with the report that the deadlock may indeed occur?

When there is a bug, it is good practice to reproduce the behavior in a test that fails on the existing code and passes on the fixed code. Some times it is very difficult, some times it is easy. The question is, how difficult is it in this case?
The reasoning behind the behavior is excellent, and it seems that the fix is doing its  job. However, we thought that the previous change was fine too, so some extra testing could add more confidence, in my opinion.

I'll leave it up to you to decide whether you can recreate the conditions in the report, and whether it is worth the effort.

**Comment by vodsej** [comment]
I'm not so well versed in fabric codebase, but I would say it would take quite a lot of effort to write a test, that would truly verify this issue. Unfortunately I won't be any help here.

**Comment by yacovm** [comment]
> > > Is there a way to add a test case (unit, or integration) that will trigger the problem? Such that we'll know its failing in the existing code and fixed after this PR?
> > > @yacovm @vodsej any suggestions?
> > 
> > 
> > You want to add a test that attempts to make the Raft chain deadlock? Usually unit tests are written to test a specific functional scenario such that if the implementation changes, the functional scenario still works as expected.
> > I'm not sure what's the point in writing a test that attempts to deadlock the two goroutines if the fix is to move the WAL sync to a single goroutine as was in the past.
> > I think it's possible to write such a test since the raft.Node is an interface and can be mocked, but do you not agree with the report that the deadlock may indeed occur?
> 
> When there is a bug, it is good practice to reproduce the behavior in a test that fails on the existing code and passes on the fixed code. Some times it is very difficult, some times it is easy. The question is, how difficult is it in this case? The reasoning behind the behavior is excellent, and it seems that the fix is doing its job. However, we thought that the previous change was fine too, so some extra testing could add more confidence, in my opinion.
> 
> I'll leave it up to you to decide whether you can recreate the conditions in the report, and whether it is worth the effort.

I think it's possible to try at least. 

@semil do you want to take a look at this after https://github.com/hyperledger/fabric/issues/4228 ?

**Comment by tock-ibm** [comment]
@denyeart Do you think we should wait for the test before merging or merge the fix and add the test in a separate issue?

**Comment by denyeart** [comment]
@tock-ibm Typically we would want a test with the PR. If the automated test is not practical in a short timeframe, I'd at least want to see that the reviewer (you in this case) has confidence in the fix and approves the PR. For example, when I review a PR that is difficult to test in CI, I will at least try to run the PR code and try to test the logic myself. Sometimes this requires modifying the code in my local environment to get the node into the appropriate state for the test and/or adding local log statements to prove out the fix. I often use the test-network-nano-bash sample for such trials, since it is simple to update code, recompile node, and spin it up.

Is that something that is feasible here?

**Comment by tock-ibm** [comment]
> @tock-ibm Typically we would want a test with the PR. If the automated test is not practical in a short timeframe, I'd at least want to see that the reviewer (you in this case) has confidence in the fix and approves the PR. For example, when I review a PR that is difficult to test in CI, I will at least try to run the PR code and try to test the logic myself. Sometimes this requires modifying the code in my local environment to get the node into the appropriate state for the test and/or adding local log statements to prove out the fix. I often use the test-network-nano-bash sample for such trials, since it is simple to update code, recompile node, and spin it up.
> 
> Is that something that is feasible here?

@denyeart @yacovm 
I am working with @semil to define a unit test that cover the scenario described in the issue. This is the proposed flow:
- start a unit test with 3 nodes
- stop (not remove) 1 node
- add a 4th node
- order some messages 
- restart the stopped node

This has the potential to hit the problematic part. The restarted node will get the config change entry from the Ready channel and trigger the flow described in the issue. Whether a deadlock will happen is a probabilistic. It will probably be necessary to run this a few times to recreate the issue, and add some printouts at relevant places in the code.

**Comment by semil** [comment]
Please look at #4262 for the test.

**Review by tock-ibm — APPROVED** [review]

**Comment by tock-ibm** [comment]
@yacovm @denyeart @vodsej 

A unit test by @semil in #4262 recreates the bug on main, before this fix, and does not fail when applied on top of this fix. I am going to merge this one, and @semil will push the test in a separate PR.

**Comment by denyeart** [comment]
@Mergifyio backport release-2.5

**Pull request merged**
