### PR TITLE
new stack image

### PR DESCRIPTION
**Pull request by joshhus**
Signed-off-by: Josh Horton <joshh@us.ibm.com>

Existing software stack image needs updates for both legibility and text.

#### Type of change

- Improvement (improvement to code, performance, etc)
- Documentation update

#### Description

Just a new graphic image for legibility and updated text.

#### Related issues

https://github.com/hyperledger/fabric/issues/3278

### CODE REVIEW

**Comment by denyeart** [comment]
@joshhus The image to replace is https://github.com/hyperledger/fabric/blob/main/docs/source/getting_started_image2.png

**Comment by joshhus** [comment]
> @joshhus The image to replace is https://github.com/hyperledger/fabric/blob/main/docs/source/getting_started_image2.png

Yes I renamed it but somehow the .rst file didn't get included. Adding now.

**Comment by denyeart** [comment]
@joshhus Please also delete the old image, we don't want to build up extra cruft.

Also, look at the new rendering - https://hyperledger-fabric--3301.org.readthedocs.build/en/3301/getting_started.html
It looks like a mistake because the 5 bullets and the 5 stack items are all next to each other, but the order is reversed between them. If we are going to have the stack directly next to the bullets, we should reverse the order of the bullets so that they line up well. Typically in these architecture stacks the application is on top and foundation on the bottom, so I agree with the diagram, just need to re-order the bullets to match.

**Comment by joshhus** [comment]
> @joshhus Please also delete the old image, we don't want to build up extra cruft.
> 
> Also, look at the new rendering - https://hyperledger-fabric--3301.org.readthedocs.build/en/3301/getting_started.html It looks like a mistake because the 5 bullets and the 5 stack items are all next to each other, but the order is reversed between them. If we are going to have the stack directly next to the bullets, we should reverse the order of the bullets so that they line up well. Typically in these architecture stacks the application is on top and foundation on the bottom, so I agree with the diagram, just need to re-order the bullets to match.

Agreed, I hadn't gone back to check the built version yet, will do.

**Comment by joshhus** [comment]
branch fully out of sync with upstream now. easier to just stash and start over with new PR.

**Comment by joshhus** [comment]
@denyeart Okay image looks decent now. If I edited down the text too much, LMK. Previously it was too verbose IMO.

**Pull request closed without merging**
