### PR TITLE
Fix organizations typo

### PR DESCRIPTION
**Pull request by nikhil550**
#### Type of change

- Documentation update

#### Description

Cherry pick typo fix to branch release-2.1

### CODE REVIEW

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.0

**Comment by nikhil550** [comment]
@Mergifyio backport release-1.4

**Review by MHBauer — APPROVED** [review]

**Review by sykesm — APPROVED** [review]

**Comment by lindluni** [comment]
@Mergifyio refresh

**Comment by lindluni** [comment]
@Mergifyio backport release-1.4

**Comment by lindluni** [comment]
@Mergifyio backport release-1.4

**Pull request merged**
