### PR TITLE
Remove Azure Pipelines (switched to Github Actions)

### PR DESCRIPTION
**Pull request by denyeart**
With the Github Actions CI and release workflows in place, we can now remove the Azure Pipelines artifacts.

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

### CODE REVIEW

**Review by ale-linux — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergify backport release-2.5

**Comment by denyeart** [comment]
@Mergify backport release-2.4

**Comment by denyeart** [comment]
@Mergify backport release-2.3

**Comment by denyeart** [comment]
@Mergify backport release-2.2

**Pull request merged**
