### PR TITLE
`goimports -l -w` fixes

### PR DESCRIPTION
**Pull request by jt-nti**
Go 1.19 is more unforgiving

Signed-off-by: James Taylor <jamest@uk.ibm.com>

### CODE REVIEW

**Comment by denyeart** [comment]
@jt-nti Shucks, command help got out of sync, I think you'll need to `make help-docs` as well to keep the command docs in sync.
More doc info at:
https://github.com/hyperledger/fabric/blob/main/docs/source/docs_guide.md#commands-reference-updates

**Comment by jt-nti** [comment]
@denyeart confusingly it seems to be passing without the help command update- I'd added it because it fails that check when I run it locally.

**Review by denyeart — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergifyio backport release-2.5

**Comment by denyeart** [comment]
@Mergifyio backport release-2.4

**Pull request merged**
