### PR TITLE
Fabcar uses first-network instead basic-network

### PR DESCRIPTION
**Pull request by chaitanya5**
#### Type of change - 

- Documentation update

#### Description

In the fabric docs,in section Writing your first application- We learn about fabcar which uses first-network but it's mentioned in ccp path that it uses basic-network configuration.json. Intsead it uses first-network.json.

#### Related issues

<!--
Checklist (DELETE AFTER READING):

### CODE REVIEW

**Review by chaitanya5 — COMMENTED** [review]
Files changed

**Review by nikhil550 — APPROVED** [review]

**Review by guoger — CHANGES_REQUESTED** [review]
i don't think this example is using first network (it is mentioned to instruct users to terminate first network, if that's been launched before)

**Comment by chaitanya5** [comment]
> i don't think this example is using first network (it is mentioned to instruct users to terminate first network, if that's been launched before)

Don't wanna sound harsh but fabcar actually uses first-network and not basic-network, if it had used basic-network, then the ccp path that is used in the client fabric-sdk files would point the ccp path to basic-network's connection.js file instead it points to first-network's connection.json file.
I'm providing the links below of invoke.js and query.js files of fabcar which use fabric-sdk module to talk to the chain code, where the ccp path is clearly mentioned pointing to first-network's connection.json file.

https://github.com/hyperledger/fabric-samples/blob/master/fabcar/javascript/invoke.js
https://github.com/hyperledger/fabric-samples/blob/master/fabcar/javascript/query.js

**Review by guoger — APPROVED** [review]

**Comment by guoger** [comment]
@chaitanya5 my mistake, fabcar does rely on byfn now

**Pull request merged**
