### PR TITLE
Use golang 1.21.1 to fix vulnerabilities

### PR DESCRIPTION
**Pull request by yeasy**
Change-Id: I62c42a07bc4577e4c734a674878f0fe11a517edf

This patchset upgrade Go version from Go 1.20.7 to 1.21.1.

#### Type of change

- Improvement (improvement to code, performance, etc)

#### Description

There are two vulnerabilities in Go 1.20: GO-2023-2041 and GO-2023-2043,
      which exist in package html/template and are used in
      core/middleware.

The vulnerabilities are fixed in Go 1.21.1.

#### Additional details

N/A

#### Related issues

N/A

#### Release Note

N/A

### CODE REVIEW

**Comment by yeasy** [comment]
@denyeart Seems the CI env is using go 1.20.7, how can we upgrade it to go 1.21.1?

**Comment by C0rWin** [comment]
Please note there is WIP here: https://github.com/hyperledger/fabric/pull/4369, there are changes to be done beyond just switching the version of go.

**Comment by C0rWin** [comment]
> @denyeart Seems the CI env is using go 1.20.7, how can we upgrade it to go 1.21.1?

you need to update github action to use right env, though, can you please hold on while I will finish the changes to accommodate switching to 1.21?

**Comment by denyeart** [comment]
Thanks @yeasy.
 @C0rWin if you plan to resume #4369 soon we can close this one out. Of course, 1.21.1 would be the choice now.

**Comment by C0rWin** [comment]
> Thanks @yeasy. @C0rWin if you plan to resume #4369 soon we can close this one out. Of course, 1.21.1 would be the choice now.

There are a few failures to appear in UT, which I am chasing now, not sure the switch 1.21 caused them, though trying to see what is wrong.

**Comment by denyeart** [comment]
Ok, given that you have momentum already on #4369 let's close this one as a duplicate.

And yes, I expect the update to v1.21 is causing the CI failures, it is typical to need to update a few tests when moving up.

**Pull request closed without merging**
