### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by denyeart**
Update CHANGELOG.md to indicate that the changelog is now maintained in GitHub.

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

### CODE REVIEW

**Comment by denyeart** [comment]
@C0rWin it looks like the integration test failures are related to the recently merged https://github.com/hyperledger/fabric/pull/2748

**Comment by C0rWin** [comment]
> @C0rWin it looks like the integration test failures are related to the recently merged #2748

Indeed, I will take a look at it, thanks @denyeart

**Comment by C0rWin** [comment]
```
ChannelParticipation three node etcdraft network with a system channel [It] joins channels using the legacy channel creation mechanism and then removes the system channel to transition to the channel participation API 
/home/vsts/work/1/fabric/integration/raft/channel_participation_test.go:1060

  Timed out after 60.840s.
  Expected
      <channelparticipation.ChannelInfo>: {
          Name: "testchannel",
          URL: "/participation/v1/channels/testchannel",
          Status: "active",
          ConsensusRelation: "consenter",
          Height: 6,
      }
  to equal
      <channelparticipation.ChannelInfo>: {
          Name: "testchannel",
          URL: "/participation/v1/channels/testchannel",
          Status: "inactive",
          ConsensusRelation: "config-tracker",
          Height: 6,
      }

  /home/vsts/work/1/fabric/integration/raft/channel_participation_test.go:1133
```

is it also a known flake?

**Comment by denyeart** [comment]
@C0rWin Yes that is the most common flake for the last year, Param is actually investigating it now - https://jira.hyperledger.org/browse/FAB-18365

**Comment by denyeart** [comment]
@C0rWin  I rebased on top of your fix but the integration test is still failing.

**Comment by C0rWin** [comment]
> @C0rWin I rebased on top of your fix but the integration test is still failing.

Can you give a try with this one? https://github.com/hyperledger/fabric/pull/2779

**Comment by C0rWin** [comment]
@denyeart I guess it's better now, right?

**Review by C0rWin — APPROVED** [review]

**Pull request merged**
