### PR TITLE
push down the peer started log

### PR DESCRIPTION
**Pull request by hello2mao**
#### Type of change

- Improvement (improvement to code, performance, etc)

#### Description

Push down the log statement until the peer has actually been started.

#### Additional details
NA

#### Related issues

NA

### CODE REVIEW

**Comment by lindluni** [comment]
If anything this should be pushed down the function, until the peer has actually been started instead of removing it.

This log statement is part of the integration suites startup verification sequence which is why your tests are failing: https://github.com/hyperledger/fabric/blob/master/integration/nwo/network.go#L1220

**Comment by sykesm** [comment]
@hello2mao what is motivating this change? 

Originally it was being removed and now it’s being moved.

The readiness message does have a purpose and is desired so I’m confused about the goal.

**Comment by hello2mao** [comment]
> @hello2mao what is motivating this change?
> 
> Originally it was being removed and now it’s being moved.
> 
> The readiness message does have a purpose and is desired so I’m confused about the goal.

@sykesm I just want to put the log to the right place where peer has actually been started. if it is unnecessary, I will close the pr. Thanks.

**Pull request closed without merging**
