### PR TITLE
doc: Update peer command help to add packageFiles argument

### PR DESCRIPTION
**Pull request by jmmunoz-kolokium**
#### Type of change

- Documentation update

#### Description

The help information for peer command is missing the package file parameter which should come after the word "install"

#### Additional details

Fix help information _"peer lifecycle chaincode install  [flags]"_ with _"peer lifecycle chaincode install [packageFiles] [flags]"_

#### Related issues

[Missing argument in help information for command "peer lifecycle chaincode install](https://github.com/hyperledger/fabric/issues/4976)

### CODE REVIEW

**Review by satota2 — CHANGES_REQUESTED** [review]
@jmmunoz-kolokium 
Thank you for submitting the PR. Could you please confirm the following two comments?

### Comment 1
- When updating the `peer` command reference, there's a slightly special procedure to follow. You need to update `fabric/internal/peer/lifecycle/chaincode/install.go` as well, following the steps outlined in the documentation.
  - Please refer to the official guide on [commands reference updates](https://hyperledger-fabric.readthedocs.io/en/latest/docs_guide.html#commands-reference-updates).

Here is a concrete example of the steps to follow:
1. Update the relevant line in `fabric/internal/peer/lifecycle/chaincode/install.go`.
2. Build the `peer` binary with the following commands (make sure to delete the existing `peer` binary in `build/bin` if it exists before rebuilding).
   ```bash
   $ cd fabric
   $ make peer
   Building build/bin/peer...
   $./build/bin/peer lifecycle chaincode install --help
   ```
3. Update the command reference (on the documentation side) by running:
   ```bash
   $ make help-docs
   ```
- I found a similar issue and submitted a PR for it. Please refer to my PR for more details:
    - https://github.com/hyperledger/fabric/pull/4993

### Comment 2

Instead of merging from your feature branch ([jmmunoz-kolokiumupdate-peer-command-help](https://github.com/jmmunoz-kolokium/kolokium-update_peer_help/tree/jmmunoz-kolokiumupdate-peer-command-help)) into the forked GitHub repository’s main branch and then submitting a PR to the original Fabric repository, you should submit the PR directly from the jmmunoz-kolokiumupdate-peer-command-help branch to the original Fabric repository.

For proper procedures on opening a PR, please refer to:
https://hyperledger-fabric.readthedocs.io/en/latest/github/github.html#opening-a-pull-request-in-github

**Comment by jmmunoz-kolokium** [comment]
Hi @satota2 , thanks again for your help.

I have read carefully your instruction and the official guides and I hope I have fullfilled the PR accordingly.

https://github.com/hyperledger/fabric/pull/5011


Best regards

**Comment by jmmunoz-kolokium** [comment]
PR reopen

**Comment by satota2** [comment]
@jmmunoz-kolokium Thank you for your update. I'll review the new PR.

**Pull request closed without merging**
