### PR TITLE
Add Language Argument to DeployCC Calls

### PR DESCRIPTION
**Pull request by jcastrence**
Signed-off-by: Julian Castrence <juliancastrence@ibm.com>

#### Type of change

- Improvement (improvement to code, performance, etc)
- Documentation update

#### Description

- DeployCC calls should now require chaincode name, chaincode path, and chaincode language arguments. Added missing chaincode language arguments to deployCC calls.

### CODE REVIEW

**Review by ale-linux — COMMENTED** [review]
I must admit I haven't tried to use the script - is the `ccl` argument mandatory or optional?

**Review by nikhil550 — APPROVED** [review]
It will be mandatory in the future.

**Comment by nikhil550** [comment]
@mergify backport release-2.3

**Comment by nikhil550** [comment]
@mergifyio backport release-2.2

**Pull request merged**
