### PR TITLE
Fix spelling mistakes in the Github Contributions page

### PR DESCRIPTION
**Pull request by nikhil550**
Signed-off-by: Nikhil Gupta <ngupta@symbridge.com>

#### Type of change

- Bug fix
- Documentation update

### CODE REVIEW

**Review by denyeart — APPROVED** [review]

**Comment by nikhil550** [comment]
@mergifyio backport release-2.3

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.2

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.1

**Comment by nikhil550** [comment]
@Mergifyio backport release-2.0

**Pull request merged**
