### PR TITLE
Fix link in Develop apps doc

### PR DESCRIPTION
**Pull request by joealewine**
Link to Transaction flow doc was broken

Change-Id: I139dcb028a3bee419ee0537c5d0541d9c5e11b05
Signed-off-by: joe-alewine <Joe.Alewine@ibm.com>

#### Type of change

- Documentation update

### CODE REVIEW

**Review by sykesm — APPROVED** [review]

**Comment by joealewine** [comment]
@Mergifyio backport release-2.2

**Comment by joealewine** [comment]
@Mergifyio backport release-2.1

**Comment by joealewine** [comment]
@Mergifyio backport release-2.0

**Comment by joealewine** [comment]
@Mergifyio backport release-1.4

**Pull request merged**
