### PR TITLE
Improves image size for better readability

### PR DESCRIPTION
**Pull request by sibelly**
#### Type of change

- Documentation update

#### Description

Removes the height of the image *getting_started_image2.png* to improve the readability.

#### Additional details

Screenshot from 2022-09-23 15-29-37

### CODE REVIEW

**Review by Param-S — COMMENTED** [review]
Can we increase the height pixel value to higher value rather than removing it. If we remove the value, it is dynamic and depends on the compiler.  I tried with the value `:height: 200px`, it is readable.

**Comment by Param-S** [comment]
LGTM

**Review by ale-linux — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergifyio backport release-2.5

**Comment by denyeart** [comment]
@Mergifyio backport release-2.4

**Pull request merged**
