### PR TITLE
updated minor typo

### PR DESCRIPTION
**Pull request by Mikearaya**
#### Type of change

- Bug fix
- New feature
- Improvement (improvement to code, performance, etc)
- Test update
- Documentation update

### CODE REVIEW

**Comment by pamandrejko** [comment]
I have updated this topic (see https://github.com/hyperledger/fabric/pull/307). When it is merged this problem no longer exists.

**Comment by denyeart** [comment]
Need to add a sign-off, e.g. "git commit -s".

**Comment by lindluni** [comment]
@Mikearaya Can you do a `git checkout patch-1 && git commit -s --amend --no-edit && git push origin patch-1 -f`

**Comment by sykesm** [comment]
Pam’s changes supersede this PR.

**Pull request closed without merging**
