### PR TITLE
Update endorsementpolicies.md

### PR DESCRIPTION
**Pull request by parwinderau**
Sentence corrected for clear explanation

#### Type of change

- Documentation update

### CODE REVIEW

**Review by ale-linux — DISMISSED** [review]

**Comment by sykesm** [comment]
@parwinderau Thank you for improving our documentation!

I know it's a pain but, in order to merge this change, the commit needs to be ["signed off"](https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#legal-stuff) to acknowledge agreement with the terms of the DCO.

Any chance you can amend your commit to include a 'Signed-off-by" trailer?

Thanks.

**Comment by parwinderau** [comment]
Dear Matthews,

Yes I have commit it again with the requested signed off statement.

BR
Parwinder

**Comment by sykesm** [comment]
> Yes I have commit it again with the requested signed off statement.

Thank you. Unfortunately, you added a new commit with the signoff instead of amending the original commit so the tooling is still complaining. 

Can you please drop the second commit and amend the first? One way to do that would be
```
$ git reset HEAD~ --hard                     # this drops the second commit
$ git commit --amend --signoff --no-edit     # this adds the signoff to the first commit
```

After that's done, you can run `git show` to make sure the commit looks correct and then push it back to your fork with the `--force` option. This will take care of the signoff and then we can merge your change. If you don't want to do that, let us know and we can update the docs on your behalf.

Thanks.

**Comment by sykesm** [comment]
Looks like #2165 was opened for the same change.

**Comment by parwinderau** [comment]
Do I need to take any action as the pull request 2165 is already merged.

BR
Parwinder

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by parwinderau** [comment]
Sorry it's not 2165 rather it's 2161

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
