### PR TITLE
Use the errors.Is to check error type

### PR DESCRIPTION
**Pull request by yeasy**
The patchset uses errors.Is to check error type.

Change-Id: Ieae0eaa2527d05fa67aa31afdda42d150fff0980

#### Type of change

- Improvement (improvement to code, performance, etc)

#### Description

errors.Is is recommened since Go 1.13 to check error type. The error may be wrapped.

More details: https://github.com/golang/go/wiki/ErrorValueFAQ.

#### Additional details

N/A

#### Related issues

N/A

#### Release Note

N/A

### CODE REVIEW

**Comment by denyeart** [comment]
In many of these files the `errors` package is actually the `github.com/pkg/errors` package which is archived and we are considering transitioning away from it.  I'm thinking we shouldn't increase the usage of the archived package at this time, let's see what comes out of the discussion in #4468.

**Comment by yeasy** [comment]
> In many of these files the `errors` package is actually the `github.com/pkg/errors` package which is archived and we are considering transitioning away from it. I'm thinking we shouldn't increase the usage of the archived package at this time, let's see what comes out of the discussion in #4468.

Correct. 
However, the `Is()` method is supported by the official `errors` pkg if you look at https://github.com/golang/go/wiki/ErrorValueFAQ. This patchset does not change the pkg name (we can migrate `github.com/pkg/errors` to `errors` later without changing the `Is()`) now because of the discussions in #4468.

**Review by denyeart — APPROVED** [review]
Ok, I agree this is moving in the correct direction, merging.
But I still think we should give #4468 some more time before opening additional PRs.

**Comment by yeasy** [comment]
> Ok, I agree this is moving in the correct direction, merging. But I still think we should give #4468 some more time before opening additional PRs.

Agree. Once we made the decision on #4468, I will continue the migration work.

**Pull request merged**
