### PR TITLE
fix error "runtime error: index out of range [0] with length 0"

### PR DESCRIPTION
**Pull request by pfi79**
fix for this [error](https://github.com/hyperledger/fabric/actions/runs/7764041048/job/21228336098)

### CODE REVIEW

**Comment by denyeart** [comment]
Thank you!  I'm hitting the error consistently while trying to update dependencies. Even with your suggested update I'm still hitting the error. I'll look into root cause...

**Comment by pfi79** [comment]
> Thank you! I'm hitting the error consistently while trying to update dependencies. Even with your suggested update I'm still hitting the error. I'll look into root cause...

I see what this is about. I'll fix it. The grpc has been updated and the log text in it has changed.

hyperledger/fabric/integration/smartbft/smartbft_test.go 1646 line. need to be replaced
```
pickfirstBalancer: UpdateSubConnState.*IDLE connection error
```
on
```
Received SubConn state update:.*IDLE ConnectionError
```

**Comment by pfi79** [comment]
hyperledger/fabric/integration/gateway/gateway_bft_test.go

line 236 need to be replaced
```
pickfirstBalancer: UpdateSubConnState.*%d
```
on
```
Received SubConn state update:
```

line 242 need to be replaced (don't forget the space at the end of the line)
```
pickfirstBalancer: UpdateSubConnState: 
```
on
```
Received SubConn state update: 
```

**Comment by denyeart** [comment]
Thank you, I've updated https://github.com/hyperledger/fabric/pull/4664 accordingly. I'll close this one now.

**Pull request closed without merging**
