### PR TITLE
stack image and text

### PR DESCRIPTION
**Pull request by joshhus**
Signed-off-by: Josh Horton <joshh@us.ibm.com>

redo on stack image, text, and links.

#### Type of change

- Improvement (improvement to code, performance, etc)
- Documentation update

#### Description

- add link for app layer
- reverse text to match image stack sequence
- new image that fits

#### Related issues

https://github.com/hyperledger/fabric/issues/3278

### CODE REVIEW

**Comment by denyeart** [comment]
The image looks good now.

The text seems insufficient. The prior page had too little context in my opinion for new users to get started, the new page reduces it further down to just 3 words per stack item. Imagine being a new user and coming to this page to "Get Started". I'd ask myself these questions upon seeing this page... What is the role of each stack item? Where do I start? What task does each link take me to? Which links must I traverse to get a minimal working environment?

It seems at minimum for each stack item we need one sentence describing the stack item role and one sentence introducing what the respective link will accomplish.

**Review by ErDanieh — APPROVED** [review]

**Comment by denyeart** [comment]
@joshhus Do you plan to re-visit this one based on the review comments?

**Comment by ale-linux** [comment]
@yacovm couldn't we merge this anyway and handle the less-than-ideal text in a subsequent PR - wdyt?

**Comment by yacovm** [comment]
> @yacovm couldn't we merge this anyway and handle the less-than-ideal text in a subsequent PR - wdyt?

I'll defer non-technical decisions such as this, to @denyeart  :-)

**Comment by denyeart** [comment]
The image has been improved in another PR recently.
The text in this PR in my opinion moves us in the wrong direction.
And since there has been no movement on this PR in months, I'll go ahead and close it.

**Pull request closed without merging**
