### PR TITLE
Fixes typo from Hardened to Hardware

### PR DESCRIPTION
**Pull request by Lazar955**
Fixes typo from "Hardened Security Modules" to "Hardware Security Modules". Source: https://en.wikipedia.org/wiki/Hardware_security_module

#### Type of change

- Documentation update

#### Description
As I have experience with HSMs the "Hardened" typo made me submit this typo fix PR.

### CODE REVIEW

**Comment by lindluni** [comment]
Thank you for the contribution, we do need you to sign off on your commit, you can do this by doing a `git commit --amend --no-edit --signoff`.

Also contributions are first made to the master branch and then backported as appropriate. If you could also reopen this commit against the master branch, we will then cherry-pick it against the `release-2.3` and `release-2.2` branches.

Thank you again!

**Comment by Lazar955** [comment]
> Thank you for the contribution, we do need you to sign off on your commit, you can do this by doing a `git commit --amend --no-edit --signoff`.
> 
> Also contributions are first made to the master branch and then backported as appropriate. If you could also reopen this commit against the master branch, we will then cherry-pick it against the `release-2.3` and `release-2.2` branches.
> 
> Thank you again!

Hey there. Np it's a small fix. I have executed the command but can't push to `pr/2169` for some reason (getting 403), am I missing something? So just open another PR on the master branch?

**Review by ale-linux — COMMENTED** [review]
It might be easiest if you just close it and re-open it if you don't manage to rebase and push again. Don't forget to amend the commit message and add the sign-off

**Comment by Lazar955** [comment]
> It might be easiest if you just close it and re-open it if you don't manage to rebase and push again. Don't forget to amend the commit message and add the sign-off

Ok, thanks. Closing and re-opening on the master branch.

**Pull request closed without merging**
