### PR TITLE
add `export CORE_PEER_TLS_ENABLED=true`

### PR DESCRIPTION
**Pull request by punkrokk**
add `export CORE_PEER_TLS_ENABLED=true` so we actually use TLS to invoke the chaincode

#### Type of change

- Bug fix

#### Description

Example doesn't work otherwise.

### CODE REVIEW

**Review by nikhil550 — DISMISSED** [review]

**Comment by nikhil550** [comment]
@punkrokk Thank you for contributing this. To get this merged, you need to sign your commit.

Try git commit --amend -s to sign this PR.

**Comment by caod123** [comment]
@lindluni did you intentionally change the base branch from `master` back to `release-2.2`?

**Comment by lindluni** [comment]
> @lindluni did you intentionally change the base branch from `master` back to `release-2.2`?

I did, the original PR was opened against master. The PR however was written on top of release-2.2 so its history was incorrect. The contribution should be rewritten on top of master and recontributed. You can see the divergent history if you switch it back to master.

**Review by nikhil550 — APPROVED** [review]

**Comment by nikhil550** [comment]
@punkrokk For a one line doc change, its probably worth starting over. I can add this change if you want, though I do not want to rob you of your contribution.

You can open against master, and then backport.

**Comment by caod123** [comment]
@punkrokk You can either resubmit the PR or you can reset your branch back to master and then cherry pick your commit on top of it and force push
```
git reset --hard master && git cherry-pick f31c8e00cca08d2bd080a2ea31f10a5b7f80e9ad
```

**Pull request closed without merging**
