### PR TITLE
Use safe accessors for RWset protos

### LINKED ISSUE #3685: Peer Node Crash When Executing ChainCode
Fabric version: 2.4.6

When we invoked chaincode from our program the related peer node crash with the following error: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1580fc9]

goroutine 114930 [running]:
github.com/hyperledger/fabric/internal/pkg/gateway.rwsetDifference({0xc002d9fe40?, 0x142?, 0x160?}, {0xc002f18000, 0x142, 0x160})
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/apiutils.go:325 +0x1c89
github.com/hyperledger/fabric/internal/pkg/gateway.payloadDifference({0xc000025860?, 0xc002687d30?, 0xc002687d10?}, {0xc000025a40, 0x1c3, 0x1e0})
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/apiutils.go:278 +0x145
github.com/hyperledger/fabric/internal/pkg/gateway.(*plan).processEndorsement(0xc002e6f380, 0xc002eb43c0, 0xc003085f20)
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/endorsement.go:123 +0x5fe
github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).processProposal(0xc00268c300, {0x1b56198?, 0xc00288eb70}, 0xc002e6f100?, 0xc002eb43c0, 0xc002e600f0, 0xc0035f2038)
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:263 +0x62c
github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).Endorse.func1(0xc00029f750?)
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:190 +0xa6
created by github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).Endorse
	/go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:188 +0xd75
```

Any idea which area we can check to fix the error?

Thanks in advanced any guide and help given.  🙏🏻

Cheers.

### PR DESCRIPTION
**Pull request by andrew-coleman**
Use the Getter functions rather than direct access to fields in the proto structures.

Resolves #3685 

Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>

### CODE REVIEW

**Comment by bestbeforetoday** [comment]
It looks at first glance like the logic should hang together fine but I wonder if it's worth a unit test for the specific failure case (either `r` or `r.Version` are `nil` in `reads[r.Key] = r.Version.BlockNum`?), just to be sure there are no knock-on issues, and that knock-on issues aren't accidentally introduced in the future

**Comment by ale-linux** [comment]
Thanks - I'm definitely in favour of this change - I'm just wondering whether other files might have the same issue and whether we should also fix them?

**Comment by andrew-coleman** [comment]
> Thanks - I'm definitely in favour of this change - I'm just wondering whether other files might have the same issue and whether we should also fix them?

I think all occurrences within the gateway package now use this style.  There may well be other packages that use direct access, but we should fix those in a separate PR.

**Review by denyeart — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergifyio backport release-2.5

**Comment by denyeart** [comment]
@Mergifyio backport release-2.4

**Pull request merged**
